<?php
// auto-generated by PropelCidesa
// date: 2017/02/17 10:59:17
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_actions.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('list'), 'faciudad/list?id='.$faciudad->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
      <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
        <li><?php echo button_to(__('create'), 'faciudad/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
              