<?php
// auto-generated by PropelCidesa
// date: 2017/02/17 10:59:17
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<td colspan="3">
    <?php echo link_to($faciudad->getNomciu() ? $faciudad->getNomciu() : __('-'), 'faciudad/edit?id='.$faciudad->getId()) ?>
     - 
    <?php echo $faciudad->getNomedo() ?>
     - 
    <?php echo $faciudad->getNompai() ?>
     - 
</td>