<?php
// auto-generated by PropelCidesa
// date: 2017/02/17 10:59:17
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_nomciu">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/faciudad/sort') == 'nomciu'): ?>
      <?php echo link_to(__('Nombre'), 'faciudad/list?sort=nomciu&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/faciudad/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/faciudad/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nombre'), 'faciudad/list?sort=nomciu&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomedo">
        <?php echo __('Estado') ?>
          </th>
  <th id="sf_admin_list_th_nompai">
        <?php echo __('País') ?>
          </th>
