<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/17 10:34:30
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlminvfis 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _filters.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('alminvfis/list', array('method' => 'get','name'=>'sf_admin_filters_form')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_fecinv"><?php echo __('Fecha Inventario:') ?></label>
    <div class="content">
    <?php echo input_date_range_tag('filters[fecinv]', isset($filters['fecinv']) ? $filters['fecinv'] : null, array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'date_format' => 'dd/MM/yy',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_codalm"><?php echo __('Almacen:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[codalm]', isset($filters['codalm']) ? $filters['codalm'] : null, array (
  'size' => 15,
  'maxlength' => 8,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_nomalm"><?php echo __('Nomalm:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[nomalm]', isset($filters['nomalm']) ? $filters['nomalm'] : null, array (
  'disabled' => true,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_codedo"><?php echo __('Codedo:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[codedo]', isset($filters['codedo']) ? $filters['codedo'] : null, array (
  'disabled' => true,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_nomedo"><?php echo __('Nomedo:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[nomedo]', isset($filters['nomedo']) ? $filters['nomedo'] : null, array (
  'disabled' => true,
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'alminvfis/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_fecinv)
	    {
	    	obj = document.sf_admin_filters_form.filters_fecinv;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_codalm)
	    {
	    	obj = document.sf_admin_filters_form.filters_codalm;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_codart)
	    {
	    	obj = document.sf_admin_filters_form.filters_codart;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_exiact)
	    {
	    	obj = document.sf_admin_filters_form.filters_exiact;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_exiact2)
	    {
	    	obj = document.sf_admin_filters_form.filters_exiact2;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_codubi)
	    {
	    	obj = document.sf_admin_filters_form.filters_codubi;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_fectras)
	    {
	    	obj = document.sf_admin_filters_form.filters_fectras;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
