<?php
// auto-generated by sfValidatorConfigHandler
// date: 2017/02/13 06:41:39

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validatorManager->registerName('rupcat', 1, 'Debe Seleccionar la Cantidad de Categorías', 'cpdefniv', null, false);
  $validatorManager->registerName('ruppar', 1, 'Debe Seleccionar la Cantidad de Partidas', 'cpdefniv', null, false);
  $validatorManager->registerName('nivdis', 1, 'Debe Seleccionar el Nivel de Disponibilidad', 'cpdefniv', null, false);
  $validatorManager->registerName('forpre', 1, 'No puede salvar sin tener un formato de Código Presupuestario', 'cpdefniv', null, false);
  $validatorManager->registerName('fecini', 1, 'No puede salvar sin introducir la Fecha de Inicio del Ejercicio', 'cpdefniv', null, false);
  $validatorManager->registerName('feccie', 1, 'No puede salvar sin introducir la Fecha de Fin del Ejercicio', 'cpdefniv', null, false);
  $validatorManager->registerName('fecper', 1, 'No puede salvar sin introducir la Fecha del Período', 'cpdefniv', null, false);
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
