<?php
// auto-generated by sfValidatorConfigHandler
// date: 2017/02/13 06:42:12

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['Validator_codpre'] = new sfPropelUniqueValidator();
  $validators['Validator_codpre']->initialize($context, array (
  'class' => 'Cpdeftit',
  'column' => 'codpre',
  'unique_error' => 'El Codigo ya Existe intente con otro',
  'min' => 1,
  'min_error' => 'El Codigo no puede tener menos de 1 caracteres',
  'max' => 50,
  'max_error' => 'El Codigo no puede tener mas de 50 caracteres',
));
  $validators['Validator_MyString2'] = new sfStringValidator();
  $validators['Validator_MyString2']->initialize($context, array (
  'min' => 1,
  'min_error' => 'La Descripción debe tener al menos un caracter',
  'max' => 500,
  'max_error' => 'La Descripción no puede tener mas de 500 caracteres',
));
  $validators['Validator_existe'] = new CidesaExistValidator();
  $validators['Validator_existe']->initialize($context, array (
  'class' => 'Contabb',
  'column' => 'codcta',
  'unique_error' => 'La Cuenta Contable no existe.',
));
  $validatorManager->registerName('codpre', 1, 'Debe llenar el codigo Presupuestario', 'cpdeftit', null, false);
  $validatorManager->registerValidator('codpre', $validators['Validator_codpre'], 'cpdeftit');
  $validatorManager->registerName('nompre', 1, 'Debe llenar la descripcion de codigo presupuestario', 'cpdeftit', null, false);
  $validatorManager->registerValidator('nompre', $validators['Validator_MyString2'], 'cpdeftit');
  $validatorManager->registerName('codcta', 0, 'Required', 'cpdeftit', null, false);
  $validatorManager->registerValidator('codcta', $validators['Validator_existe'], 'cpdeftit');
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
