<?php
// auto-generated by sfViewConfigHandler
// date: 2017/02/13 05:46:19
$context  = $this->getContext();
$response = $context->getResponse();

if ($this->actionName.$this->viewName == 'mensajeSuccess')
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'mensajeSuccess')
{
  $this->setDecoratorTemplate('layout_generales'.$this->getExtension());
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Módulo Recursos Humanos', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Módulo Recursos Humanos', false, false);
  $response->addMeta('keywords', 'Módulo Recursos Humanos', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('dFilter', '');
}
else
{
  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Módulo Nómina', false, false);
  $response->addMeta('robots', 'index, follow', false, false);
  $response->addMeta('description', 'Módulo Nómina', false, false);
  $response->addMeta('keywords', 'Módulo Nómina', false, false);
  $response->addMeta('language', 'en', false, false);

  $response->addStylesheet('main', '', array ());
  $response->addJavascript('/sf/prototype/js/prototype', '');
  $response->addJavascript('/sf/prototype/js/scriptaculous', '');
  $response->addJavascript('tools', '');
  $response->addJavascript('observe', '');
  $response->addJavascript('ajax', '');
  $response->addJavascript('dFilter', '');
}

