<?php
// auto-generated by PropelCidesa
// date: 2015/04/23 16:18:45
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>
<?php $cambiareti=H::getConfApp2('cameti', 'viaticos', 'viasolviatra');?>
  <th id="sf_admin_list_th_numsol">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/viasolviatra/sort') == 'numsol'): ?>
      <?php if ($cambiareti=="S") echo link_to(__('Nro Orden'), 'viasolviatra/list?sort=numsol&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort') == 'asc' ? 'desc' : 'asc')); else echo link_to(__('Nro Solicitud'), 'viasolviatra/list?sort=numsol&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort') == 'asc' ? 'desc' : 'asc')); ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort')) ?>)
      <?php else: ?>
      <?php if ($cambiareti=="S") echo link_to(__('Nro Orden'), 'viasolviatra/list?sort=numsol&type=asc'); else echo link_to(__('Nro Solicitud'), 'viasolviatra/list?sort=numsol&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_fecsol">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/viasolviatra/sort') == 'fecsol'): ?>
      <?php if ($cambiareti=="S") echo link_to(__('Fecha Orden'), 'viasolviatra/list?sort=fecsol&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort') == 'asc' ? 'desc' : 'asc')); else echo link_to(__('Fecha Solicitud'), 'viasolviatra/list?sort=fecsol&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort') == 'asc' ? 'desc' : 'asc')); ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort')) ?>)
      <?php else: ?>
      <?php if ($cambiareti=="S") echo link_to(__('Fecha Orden'), 'viasolviatra/list?sort=fecsol&type=asc'); else echo link_to(__('Fecha Solicitud'), 'viasolviatra/list?sort=fecsol&type=asc'); ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_codemp">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/viasolviatra/sort') == 'codemp'): ?>
      <?php echo link_to(__('Empleado'), 'viasolviatra/list?sort=codemp&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/viasolviatra/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Empleado'), 'viasolviatra/list?sort=codemp&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomemp">
        <?php echo __('Nomemp') ?>
          </th>
  <th id="sf_admin_list_th_nivel">
        <?php echo __('Nivel Organizacional') ?>
          </th>
  <th id="sf_admin_list_th_status2">
        <?php echo __('Status') ?>
          </th>
  <th id="sf_admin_list_th_tipvia2">
        <?php echo __('Tipo') ?>
          </th>
