<?php
// auto-generated by PropelCidesa
// date: 2017/02/13 05:46:41
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php echo form_tag('nomcamnomcar/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($npasicaremp, 'getId') ?>

<?php
  $fields = NpasicarempPeer::getFieldNames();

  if(array_search('Codalmusu', $fields))
  {  ?>
  <h2 class="h2" onclick="javascript: return $('divusualms').toggle();"><?php echo __('Almacenes') ?></h2>
  <fieldset id="sf_fieldset_usualms" class="">
  <div class="form-row" id="divusualms">
    <?php echo label_for('npasicaremp[codalmusu]', __('Almacenes Por Usuario: '), 'class="required" Style="text-align:left; width:150px"') ?>
    <div class="content">
    <?php
      $almacenes = $sf_user->getAttribute('usualms',array());
      if(count($almacenes)>0){
        $keys = array_keys($almacenes);
        $codalm = $keys[0];
      }else $codalm = '';
      if($codalm == '') echo label_for('npasicaremp[codalmusu]', __('Usuario sin Almacen Asociado'), 'class="required" Style="text-align:left; width:150px"').'<br><br><br>';
      else echo select_tag('npasicaremp[codalmusu]',options_for_select($almacenes,$npasicaremp->getCodalmusu()!='' ? $npasicaremp->getCodalmusu() : $codalm), ( ($npasicaremp->getId()) ? 'disabled=true' : '').' style=width:500px');
    ?>
    </div>
  </div>
  </fieldset>
<?php } ?>



<h2 class="h2" onclick="javascript: return $('divInformación Empleado').toggle();"><?php echo __('Información Empleado') ?></h2>
<fieldset id="sf_fieldset_informaci__n_empleado" class="">

<div class="form-row" id="divInformación Empleado">
<div id="divcodemp">
  <?php if($labels['npasicaremp{codemp}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codemp]', __($labels['npasicaremp{codemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codemp}')): ?>
    <?php echo form_error('npasicaremp{codemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($npasicaremp, 'getCodemp', array (
  'size' => 20,
  'control_name' => 'npasicaremp[codemp]',
  'readonly' => true,
  'style' => 'border:none',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcedemp">
  <?php if($labels['npasicaremp{cedemp}']!='.:') { ?>
  <?php echo label_for('npasicaremp[cedemp]', __($labels['npasicaremp{cedemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{cedemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{cedemp}')): ?>
    <?php echo form_error('npasicaremp{cedemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($npasicaremp, 'getCedemp', array (
  'disabled' => true,
  'control_name' => 'npasicaremp[cedemp]',
  'readonly' => true,
  'style' => 'border:none',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{cedemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnomemp">
  <?php if($labels['npasicaremp{nomemp}']!='.:') { ?>
  <?php echo label_for('npasicaremp[nomemp]', __($labels['npasicaremp{nomemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{nomemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{nomemp}')): ?>
    <?php echo form_error('npasicaremp{nomemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($npasicaremp, 'getNomemp', array (
  'size' => 80,
  'control_name' => 'npasicaremp[nomemp]',
  'readonly' => true,
  'style' => 'border:none',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{nomemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecing">
  <?php if($labels['npasicaremp{fecing}']!='.:') { ?>
  <?php echo label_for('npasicaremp[fecing]', __($labels['npasicaremp{fecing}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{fecing}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{fecing}')): ?>
    <?php echo form_error('npasicaremp{fecing}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($npasicaremp, 'getFecing', array (
  'disabled' => true,
  'control_name' => 'npasicaremp[fecing]',
  'readonly' => true,
  'style' => 'border:none',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{fecing}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divInformación de Nomina Actual del Empleado').toggle();"><?php echo __('Información de Nomina Actual del Empleado') ?></h2>
<fieldset id="sf_fieldset_informaci__n_de_nomina_actual_del_empleado" class="">

<div class="form-row" id="divInformación de Nomina Actual del Empleado">
<div id="divcodnom">
  <?php if($labels['npasicaremp{codnom}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codnom]', __($labels['npasicaremp{codnom}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codnom}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codnom}')): ?>
    <?php echo form_error('npasicaremp{codnom}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codnom', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codnom}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcar">
  <?php if($labels['npasicaremp{codcar}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codcar]', __($labels['npasicaremp{codcar}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codcar}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codcar}')): ?>
    <?php echo form_error('npasicaremp{codcar}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codcar', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codcar}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcat">
  <?php if($labels['npasicaremp{codcat}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codcat]', __($labels['npasicaremp{codcat}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codcat}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codcat}')): ?>
    <?php echo form_error('npasicaremp{codcat}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codcat', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codcat}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodtipemp">
  <?php if($labels['npasicaremp{codtipemp}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codtipemp]', __($labels['npasicaremp{codtipemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codtipemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codtipemp}')): ?>
    <?php echo form_error('npasicaremp{codtipemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codtipemp', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codtipemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodniv2">
  <?php if($labels['npasicaremp{codniv2}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codniv2]', __($labels['npasicaremp{codniv2}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codniv2}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codniv2}')): ?>
    <?php echo form_error('npasicaremp{codniv2}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codniv2', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codniv2}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divInformación de Cambio').toggle();"><?php echo __('Información de Cambio') ?></h2>
<fieldset id="sf_fieldset_informaci__n_de_cambio" class="">

<div class="form-row" id="divInformación de Cambio">
<div id="divfecha">
  <?php if($labels['npasicaremp{fecha}']!='.:') { ?>
  <?php echo label_for('npasicaremp[fecha]', __($labels['npasicaremp{fecha}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{fecha}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{fecha}')): ?>
    <?php echo form_error('npasicaremp{fecha}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('fecha', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{fecha}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divpdesmotcamcar">
  <?php if($labels['npasicaremp{pdesmotcamcar}']!='.:') { ?>
  <?php echo label_for('npasicaremp[pdesmotcamcar]', __($labels['npasicaremp{pdesmotcamcar}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{pdesmotcamcar}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{pdesmotcamcar}')): ?>
    <?php echo form_error('npasicaremp{pdesmotcamcar}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('pdesmotcamcar', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{pdesmotcamcar}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodnomnew">
  <?php if($labels['npasicaremp{codnomnew}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codnomnew]', __($labels['npasicaremp{codnomnew}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codnomnew}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codnomnew}')): ?>
    <?php echo form_error('npasicaremp{codnomnew}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codnomnew', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codnomnew}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcarnew">
  <?php if($labels['npasicaremp{codcarnew}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codcarnew]', __($labels['npasicaremp{codcarnew}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codcarnew}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codcarnew}')): ?>
    <?php echo form_error('npasicaremp{codcarnew}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codcarnew', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codcarnew}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcatnew">
  <?php if($labels['npasicaremp{codcatnew}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codcatnew]', __($labels['npasicaremp{codcatnew}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codcatnew}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codcatnew}')): ?>
    <?php echo form_error('npasicaremp{codcatnew}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codcatnew', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codcatnew}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodtipempnew">
  <?php if($labels['npasicaremp{codtipempnew}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codtipempnew]', __($labels['npasicaremp{codtipempnew}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codtipempnew}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codtipempnew}')): ?>
    <?php echo form_error('npasicaremp{codtipempnew}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codtipempnew', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codtipempnew}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodniv2new">
  <?php if($labels['npasicaremp{codniv2new}']!='.:') { ?>
  <?php echo label_for('npasicaremp[codniv2new]', __($labels['npasicaremp{codniv2new}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{codniv2new}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{codniv2new}')): ?>
    <?php echo form_error('npasicaremp{codniv2new}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codniv2new', array('type' => 'edit', 'npasicaremp' => $npasicaremp,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{codniv2new}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divjuscam">
  <?php if($labels['npasicaremp{juscam}']!='.:') { ?>
  <?php echo label_for('npasicaremp[juscam]', __($labels['npasicaremp{juscam}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('npasicaremp{juscam}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npasicaremp{juscam}')): ?>
    <?php echo form_error('npasicaremp{juscam}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($npasicaremp, 'getJuscam', array (
  'control_name' => 'npasicaremp[juscam]',
  'size' => '60x5',
  'maxlength' => 250,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['npasicaremp{juscam}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<?php include_partial('edit_actions', array('npasicaremp' => $npasicaremp)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>

