<?php
// auto-generated by PropelCidesa
// date: 2017/02/13 06:39:25
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<td colspan="3">
    <?php echo $fadtocte->getFatipcteId() ?>
     - 
    <?php echo $fadtocte->getCoddesc() ?>
     - 
    <?php echo link_to($fadtocte->getId() ? $fadtocte->getId() : __('-'), 'fadtocte/edit?id='.$fadtocte->getId()) ?>
     - 
</td>