<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/17 10:34:13
?>
<?php

/**
 * autoAlmentalm actions.
 *
 * @package    Roraima
 * @subpackage autoAlmentalm 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: actions.class.php 32371 2009-09-01 16:06:59Z lhernandez $
 */
class autoAlmentalmActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('almentalm', 'list');
  }

  public function executeList()
  {
    $this->processSort();

    $this->processFilters();

    $this->filters = $this->getUser()->getAttributeHolder()->getAll('sf_admin/caentalm/filters');


     // 15    // pager
    $this->pager = new sfPropelPager('Caentalm', 15);
    $c = new Criteria();
    $this->addSortCriteria($c);
    $this->addFiltersCriteria($c);
    $this->pager->setCriteria($c);
    $this->pager->setPage($this->getRequestParameter('page', 1));
    $this->pager->init();
  }

  public function executeCreate()
  {
    return $this->forward('almentalm', 'edit');
  }

  public function executeSave()
  {
    return $this->forward('almentalm', 'edit');
  }

  /**
   * Función principal para el manejo de las acciones create y edit
   * del formulario.
   *
   */
  public function executeEdit()
  {
    $this->caentalm = $this->getCaentalmOrCreate();

    if ($this->getRequest()->getMethod() == sfRequest::POST)
    {
      $this->updateCaentalmFromRequest();

      $this->saveCaentalm($this->caentalm);

      $this->setFlash('notice', 'Your modifications have been saved');

    $this->Bitacora('Guardo');

      if ($this->getRequestParameter('save_and_add'))
      {
        return $this->redirect('almentalm/create');
      }
      else if ($this->getRequestParameter('save_and_list'))
      {
        return $this->redirect('almentalm/list');
      }
      else
      {
        return $this->redirect('almentalm/edit?id='.$this->caentalm->getId());
      }
    }
    else
    {
      $this->labels = $this->getLabels();
    }
  }

  public function executeDelete()
  {
    $this->caentalm = CaentalmPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->caentalm);

    try
    {
      $this->deleteCaentalm($this->caentalm);
      $this->Bitacora('Elimino');
    }
    catch (PropelException $e)
    {
      $this->getRequest()->setError('delete', 'No se pudo borrar la registro seleccionado. Asegúrese de que no tiene ningún tipo de registros asociados.');
      return $this->forward('almentalm', 'list');
    }

    return $this->redirect('almentalm/list');
  }

  public function handleErrorEdit()
  {
    $this->preExecute();
    $this->caentalm = $this->getCaentalmOrCreate();
    $this->updateCaentalmFromRequest();

    $this->labels = $this->getLabels();

    return sfView::SUCCESS;
  }

  protected function saveCaentalm($caentalm)
  {
    $caentalm->save();

  }

  protected function deleteCaentalm($caentalm)
  {
    $caentalm->delete();
  }

  protected function updateCaentalmFromRequest()
  {
    $caentalm = $this->getRequestParameter('caentalm');

    if (isset($caentalm['rcpart']))
    {
      $this->caentalm->setRcpart($caentalm['rcpart']);
    }
    if (isset($caentalm['codalm']))
    {
      $this->caentalm->setCodalm($caentalm['codalm']);
    }
    if (isset($caentalm['codpro']))
    {
      $this->caentalm->setCodpro($caentalm['codpro']);
    }
    if (isset($caentalm['rifpro']))
    {
      $this->caentalm->setRifpro($caentalm['rifpro']);
    }
    if (isset($caentalm['desrcp']))
    {
      $this->caentalm->setDesrcp($caentalm['desrcp']);
    }
    if (isset($caentalm['monrcp']))
    {
      $this->caentalm->setMonrcp($caentalm['monrcp']);
    }
    if (isset($caentalm['tipmov']))
    {
    $this->caentalm->setTipmov($caentalm['tipmov'] ? $caentalm['tipmov'] : null);
    }
    if (isset($caentalm['fecrcp']))
    {
      if ($caentalm['fecrcp'])
      {
        try
        {
          $dateFormat = new sfDateFormat($this->getUser()->getCulture());
                              if (!is_array($caentalm['fecrcp']))
          {
            $value = $dateFormat->format($caentalm['fecrcp'], 'i', $dateFormat->getInputPattern('d'));
          }
          else
          {
            $value_array = $caentalm['fecrcp'];
            $value = $value_array['year'].'-'.$value_array['month'].'-'.$value_array['day'].(isset($value_array['hour']) ? ' '.$value_array['hour'].':'.$value_array['minute'].(isset($value_array['second']) ? ':'.$value_array['second'] : '') : '');
          }
          $this->caentalm->setFecrcp($value);
        }
        catch (sfException $e)
        {
          // not a date
        }
      }
      else
      {
        $this->caentalm->setFecrcp(null);
      }
    }
    if (isset($caentalm['codubi']))
    {
      $this->caentalm->setCodubi($caentalm['codubi']);
    }
    if (isset($caentalm['codcen']))
    {
      $this->caentalm->setCodcen($caentalm['codcen']);
    }
    if (isset($caentalm['codsada']))
    {
      $this->caentalm->setCodsada($caentalm['codsada']);
    }
    if (isset($caentalm['nroentdes']))
    {
      $this->caentalm->setNroentdes($caentalm['nroentdes']);
    }
    if (isset($caentalm['nrocarveh']))
    {
      $this->caentalm->setNrocarveh($caentalm['nrocarveh']);
    }
    if (isset($caentalm['nrocontro']))
    {
      $this->caentalm->setNrocontro($caentalm['nrocontro']);
    }
    if (isset($caentalm['coddirec']))
    {
      $this->caentalm->setCoddirec($caentalm['coddirec']);
    }
    if (isset($caentalm['observ']))
    {
      $this->caentalm->setObserv($caentalm['observ']);
    }
    if (isset($caentalm['nrocon']))
    {
      $this->caentalm->setNrocon($caentalm['nrocon']);
    }
  }

  protected function getCaentalmOrCreate($id = 'id')
  {
    if (!$this->getRequestParameter($id))
    {
      $caentalm = new Caentalm();
    }
    else
    {
      $caentalm = CaentalmPeer::retrieveByPk($this->getRequestParameter($id));

      $this->forward404Unless($caentalm);
    }

    return $caentalm;
  }

  protected function processFilters()
  {
    if ($this->getRequest()->hasParameter('filter'))
    {
      $filters = $this->getRequestParameter('filters');
      if (isset($filters['fecrcp']['from']) && $filters['fecrcp']['from'] !== '')
      {
        $filters['fecrcp']['from'] = sfI18N::getTimestampForCulture($filters['fecrcp']['from'], $this->getUser()->getCulture());
      }
      if (isset($filters['fecrcp']['to']) && $filters['fecrcp']['to'] !== '')
      {
        $filters['fecrcp']['to'] = sfI18N::getTimestampForCulture($filters['fecrcp']['to'], $this->getUser()->getCulture());
      }

      $this->getUser()->getAttributeHolder()->removeNamespace('sf_admin/caentalm/filters');
      $this->getUser()->getAttributeHolder()->add($filters, 'sf_admin/caentalm/filters');
    }
  }

  protected function processSort()
  {
    if ($this->getRequestParameter('sort'))
    {
      $this->getUser()->setAttribute('sort', $this->getRequestParameter('sort'), 'sf_admin/caentalm/sort');
      $this->getUser()->setAttribute('type', $this->getRequestParameter('type', 'asc'), 'sf_admin/caentalm/sort');
    }

    if (!$this->getUser()->getAttribute('sort', null, 'sf_admin/caentalm/sort'))
    {
      $this->getUser()->setAttribute('sort', 'rcpart', 'sf_admin/caentalm/sort');
      $this->getUser()->setAttribute('type', 'asc', 'sf_admin/caentalm/sort');
    }
  }

   protected function addFiltersCriteria($c)
  {
    if (isset($this->filters['rcpart_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::RCPART, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::RCPART, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['rcpart']) && $this->filters['rcpart'] !== '')
    {
      $c->add(CaentalmPeer::RCPART, '%'.strtr($this->filters['rcpart'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
    if (isset($this->filters['rifpro_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::RIFPRO, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::RIFPRO, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['rifpro']) && $this->filters['rifpro'] !== '')
    {
      $c->add(CaentalmPeer::RIFPRO, $this->filters['rifpro']);
    }
    if (isset($this->filters['fecrcp_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::FECRCP, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::FECRCP, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['fecrcp']))
    {
      if (isset($this->filters['fecrcp']['from']) && $this->filters['fecrcp']['from'] !== '')
      {
        $criterion = $c->getNewCriterion(CaentalmPeer::FECRCP, date('Y-m-d', $this->filters['fecrcp']['from']), Criteria::GREATER_EQUAL);
      }
      if (isset($this->filters['fecrcp']['to']) && $this->filters['fecrcp']['to'] !== '')
      {
        if (isset($criterion))
        {
          $criterion->addAnd($c->getNewCriterion(CaentalmPeer::FECRCP, date('Y-m-d', $this->filters['fecrcp']['to']), Criteria::LESS_EQUAL));
        }
        else
        {
          $criterion = $c->getNewCriterion(CaentalmPeer::FECRCP, date('Y-m-d', $this->filters['fecrcp']['to']), Criteria::LESS_EQUAL);
        }
      }

      if (isset($criterion))
      {
        $c->add($criterion);
      }
    }
    if (isset($this->filters['desrcp_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::DESRCP, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::DESRCP, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['desrcp']) && $this->filters['desrcp'] !== '')
    {
      $c->add(CaentalmPeer::DESRCP, '%'.strtr($this->filters['desrcp'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
    if (isset($this->filters['codcen_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::CODCEN, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::CODCEN, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['codcen']) && $this->filters['codcen'] !== '')
    {
      $c->add(CaentalmPeer::CODCEN, '%'.strtr($this->filters['codcen'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
    if (isset($this->filters['descen_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::DESCEN, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::DESCEN, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['descen']) && $this->filters['descen'] !== '')
    {
      $c->add(CaentalmPeer::DESCEN, $this->filters['descen']);
    }
    if (isset($this->filters['codpro_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::CODPRO, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::CODPRO, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['codpro']) && $this->filters['codpro'] !== '')
    {
      $c->add(CaentalmPeer::CODPRO, '%'.strtr($this->filters['codpro'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
    if (isset($this->filters['nompro_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::NOMPRO, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::NOMPRO, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['nompro']) && $this->filters['nompro'] !== '')
    {
      $c->add(CaentalmPeer::NOMPRO, $this->filters['nompro']);
    }
    if (isset($this->filters['codalm_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::CODALM, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::CODALM, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['codalm']) && $this->filters['codalm'] !== '')
    {
      $c->add(CaentalmPeer::CODALM, '%'.strtr($this->filters['codalm'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
    if (isset($this->filters['nomalm_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::NOMALM, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::NOMALM, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['nomalm']) && $this->filters['nomalm'] !== '')
    {
      $c->add(CaentalmPeer::NOMALM, $this->filters['nomalm']);
    }
    if (isset($this->filters['codedo_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::CODEDO, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::CODEDO, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['codedo']) && $this->filters['codedo'] !== '')
    {
      $c->add(CaentalmPeer::CODEDO, $this->filters['codedo']);
    }
    if (isset($this->filters['nomedo_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::NOMEDO, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::NOMEDO, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['nomedo']) && $this->filters['nomedo'] !== '')
    {
      $c->add(CaentalmPeer::NOMEDO, $this->filters['nomedo']);
    }
    if (isset($this->filters['codsada_is_empty']))
    {
      $criterion = $c->getNewCriterion(CaentalmPeer::CODSADA, '');
      $criterion->addOr($c->getNewCriterion(CaentalmPeer::CODSADA, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['codsada']) && $this->filters['codsada'] !== '')
    {
      $c->add(CaentalmPeer::CODSADA, '%'.strtr($this->filters['codsada'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
  }
  protected function addSortCriteria($c)
  {
    if ($sort_column = $this->getUser()->getAttribute('sort', null, 'sf_admin/caentalm/sort'))
    {
      $sort_column = CaentalmPeer::translateFieldName($sort_column, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_COLNAME);
      if ($this->getUser()->getAttribute('type', null, 'sf_admin/caentalm/sort') == 'asc')
      {
        $c->addAscendingOrderByColumn($sort_column);
      }
      else
      {
        $c->addDescendingOrderByColumn($sort_column);
      }
    }
  }

  protected function getLabels()
  {
    return array(
      'caentalm{rcpart}' => 'Número:',
      'caentalm{codalm}' => 'Código Almacen:',
      'caentalm{codpro}' => 'Cód. Contratistas de Bienes o Servicio y Cooperativas:',
      'caentalm{rifpro}' => 'RIF Contratistas de Bienes o Servicio y Cooperativas:',
      'caentalm{desrcp}' => 'Descripción:',
      'caentalm{monrcp}' => 'Monto Total:',
      'caentalm{tipmov}' => 'Tipo Movimiento:',
      'caentalm{fecrcp}' => 'Fecha:',
      'caentalm{codubi}' => 'Código de la Ubicación:',
      'caentalm{codcen}' => 'Centro de Costo:',
      'caentalm{codsada}' => 'Código SADA:',
      'caentalm{nroentdes}' => 'N° de Nota de Entrega/Despacho:',
      'caentalm{nrocarveh}' => 'N° de Orden de Carga Vehicular:',
      'caentalm{nrocontro}' => 'N° de Control:',
      'caentalm{coddirec}' => 'Dirección:',
      'caentalm{observ}' => 'Observaciones:',
      'caentalm{nrocon}' => 'N° de Contenedor:',
    );
  }

    public function executeCatalogo()
  {
    $codigo = $this->getRequestParameter('codigo','');
    $clase = $this->getRequestParameter('clase','');
    $nombre = $this->getRequestParameter('name','');
    $campobase = $this->getRequestParameter('campobase','');
    $campoprincipal = $this->getRequestParameter('campoprincipal','');
    $camposecundario = $this->getRequestParameter('camposecundario','');

    $c = new Criteria();
    eval('$c->add('.ucfirst(strtolower($clase)).'Peer::'.strtoupper($campoprincipal).','.chr(39).$codigo.chr(39).');');
    eval('$peer = '.ucfirst(strtolower($clase)).'Peer::doSelectOne($c);');

  eval('$cajasec = "'.strtolower($nombre).'_'.strtolower($camposecundario).'";');
  eval('$cajaid = "'.strtolower($nombre).'_'.strtolower($campobase).'";');
  $valsec="";
  $valid="";
  eval('if ($peer) $valsec = $peer->get'.H::ObtenerNombreCampo($camposecundario).'();');
  eval('if ($peer) $valid = $peer->getId();');
  $output = '[["'.$cajasec.'","'.$valsec.'",""],["'.$cajaid.'","'.$valid.'",""],["","",""]]';
    $this->getResponse()->setHttpHeader("X-JSON", '('.$output.')');
    return sfView::HEADER_ONLY;
  }

  public function SalvarBitacora($id, $acc)
  {
    try{
      $segbitaco= new Segbitaco();
      $fecha=date('Y-m-d');

      $segbitaco->setCodintusu($this->getUser()->getAttribute('usuario_id'));
      $segbitaco->setTipope(substr($acc, 0, 1));
      $segbitaco->setCodmod('almentalm');
      $segbitaco->setValcla('Caentalm');
      $segbitaco->setCodapl(substr(SF_APP, 0, 3));
      $segbitaco->setFecope($fecha);
      $segbitaco->setHorope(time('h:i:s'));
      $segbitaco->setRefmov($id);
      $segbitaco->save();
    }catch(Exception $e){

    }
  }

  public function Bitacora($acc)
  {
    if ($this->caentalm )
    {
      $id= $this->caentalm->getId();
      $this->SalvarBitacora($id ,$acc);
    }
  }

}
