<?php
// auto-generated by cidesaSecurityConfigHandler
// date: 2017/02/13 06:39:17
$this->security = array (
  'all' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_8',
        2 => 'faestado_15',
        3 => 'faestado_11',
        4 => 'facturacion_8',
        5 => 'facturacion_15',
        6 => 'facturacion_11',
      ),
    ),
  ),
  'index' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_8',
        2 => 'faestado_15',
        3 => 'faestado_11',
        4 => 'facturacion_8',
        5 => 'facturacion_15',
        6 => 'facturacion_11',
      ),
    ),
  ),
  'list' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_8',
        2 => 'faestado_15',
        3 => 'faestado_11',
        4 => 'facturacion_8',
        5 => 'facturacion_15',
        6 => 'facturacion_11',
      ),
    ),
  ),
  'delete' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_15',
        2 => 'facturacion_8',
        3 => 'facturacion_15',
        4 => 'facturacion_11',
      ),
    ),
  ),
  'ajaxdelete' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_15',
        2 => 'facturacion_8',
        3 => 'facturacion_15',
        4 => 'facturacion_11',
      ),
    ),
  ),
  'anular' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_15',
        2 => 'facturacion_8',
        3 => 'facturacion_15',
        4 => 'facturacion_11',
      ),
    ),
  ),
  'salvaranu' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_15',
        2 => 'facturacion_8',
        3 => 'facturacion_15',
        4 => 'facturacion_11',
      ),
    ),
  ),
  'save' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_15',
        2 => 'faestado_11',
        3 => 'facturacion_8',
        4 => 'facturacion_15',
        5 => 'facturacion_11',
      ),
    ),
  ),
  'edit' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_8',
        2 => 'faestado_15',
        3 => 'faestado_11',
        4 => 'facturacion_8',
        5 => 'facturacion_15',
        6 => 'facturacion_11',
      ),
    ),
  ),
  'create' => 
  array (
    'is_secure' => 1,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'admin',
        1 => 'faestado_11',
        2 => 'faestado_15',
        3 => 'facturacion_8',
        4 => 'facturacion_15',
        5 => 'facturacion_11',
      ),
    ),
  ),
);
