<?php
// auto-generated by PropelCidesa
// date: 2013/07/02 14:25:10
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: editSuccess.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'Catalogo') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php 
$cameti=H::getConfApp2('cameti', 'presupuesto', 'preaprcom');
if ($cameti!='') {
	echo __($cameti, 
array());
}else  {
echo __('Aprobación del Compromiso para su Causado por Lotes', 
array());
 } ?></h1>


<div id="sf_admin_header">
<?php include_partial('preaprcom/edit_header', array('cpcompro' => $cpcompro, 'labels' => $labels, 'params' => $params)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('preaprcom/edit_messages', array('cpcompro' => $cpcompro, 'labels' => $labels, 'params' => $params)) ?>
<?php include_partial('preaprcom/edit_form', array('cpcompro' => $cpcompro, 'labels' => $labels, 'params' => $params)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('preaprcom/edit_footer', array('cpcompro' => $cpcompro, 'labels' => $labels, 'params' => $params)) ?>
</div>

</div>
