<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/17 10:46:45
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmtraalm 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<?php echo form_tag('almtraalm/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($catraalm, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('catraalm[codtra]', __($labels['catraalm{codtra}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{codtra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{codtra}')): ?>
    <?php echo form_error('catraalm{codtra}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getCodtra', array (
  'size' => 20,
  'control_name' => 'catraalm[codtra]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[fectra]', __($labels['catraalm{fectra}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{fectra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{fectra}')): ?>
    <?php echo form_error('catraalm{fectra}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($catraalm, 'getFectra', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'catraalm[fectra]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[destra]', __($labels['catraalm{destra}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{destra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{destra}')): ?>
    <?php echo form_error('catraalm{destra}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getDestra', array (
  'size' => 80,
  'control_name' => 'catraalm[destra]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[almori]', __($labels['catraalm{almori}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{almori}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{almori}')): ?>
    <?php echo form_error('catraalm{almori}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getAlmori', array (
  'size' => 20,
  'control_name' => 'catraalm[almori]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[almaori]', __($labels['catraalm{almaori}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{almaori}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{almaori}')): ?>
    <?php echo form_error('catraalm{almaori}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getAlmaori', array (
  'disabled' => true,
  'control_name' => 'catraalm[almaori]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[almdes]', __($labels['catraalm{almdes}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{almdes}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{almdes}')): ?>
    <?php echo form_error('catraalm{almdes}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getAlmdes', array (
  'size' => 20,
  'control_name' => 'catraalm[almdes]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[codubiori]', __($labels['catraalm{codubiori}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{codubiori}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{codubiori}')): ?>
    <?php echo form_error('catraalm{codubiori}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getCodubiori', array (
  'size' => 20,
  'control_name' => 'catraalm[codubiori]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[almades]', __($labels['catraalm{almades}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{almades}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{almades}')): ?>
    <?php echo form_error('catraalm{almades}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getAlmades', array (
  'disabled' => true,
  'control_name' => 'catraalm[almades]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('catraalm[codubides]', __($labels['catraalm{codubides}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('catraalm{codubides}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('catraalm{codubides}')): ?>
    <?php echo form_error('catraalm{codubides}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($catraalm, 'getCodubides', array (
  'size' => 20,
  'control_name' => 'catraalm[codubides]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('catraalm' => $catraalm)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($catraalm->getId()): ?>
<?php echo button_to(__('delete'), 'almtraalm/delete?id='.$catraalm->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
