<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/17 10:46:45
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmtraalm 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<td colspan="5">
    <?php echo link_to($catraalm->getCodtra() ? $catraalm->getCodtra() : __('-'), 'almtraalm/edit?id='.$catraalm->getId()) ?>
     - 
    <?php echo ($catraalm->getFectra() !== null && $catraalm->getFectra() !== '') ? format_date($catraalm->getFectra(), "dd/MM/yyyy") : '' ?>
     - 
    <?php echo $catraalm->getDestra() ?>
     - 
    <?php echo $catraalm->getAlmori() ?>
     - 
    <?php echo $catraalm->getAlmdes() ?>
     - 
</td>