<?php
// auto-generated by sfValidatorConfigHandler
// date: 2017/02/13 06:33:16

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['UniqueValidator'] = new sfPropelUniqueValidator();
  $validators['UniqueValidator']->initialize($context, array (
  'class' => 'Cadefubi',
  'column' => 'codubi',
  'unique_error' => 'El Código de Ubicación ya existe. Por Favor, Cambiélo por otro.',
));
  $validators['MyCidesaMaskValidator'] = new CidesaMaskValidator();
  $validators['MyCidesaMaskValidator']->initialize($context, array (
  'class' => 'cadefart',
  'columnmask' => 'forubi',
  'columndiv' => 'rupart',
  'div' => 1,
));
  $validators['MyStringValidator'] = new sfStringValidator();
  $validators['MyStringValidator']->initialize($context, array (
  'min' => 1,
  'min_error' => 'La Descripción no puede tener menos de 2 caracteres',
  'max' => 100,
  'max_error' => 'La Descripción no puede pasar mas de 250 caracteres',
));
  $validatorManager->registerName('codubi', 1, 'El Código de la Ubicación no puedo estar en Blanco', 'cadefubi', null, false);
  $validatorManager->registerValidator('codubi', $validators['UniqueValidator'], 'cadefubi');
  $validatorManager->registerValidator('codubi', $validators['MyCidesaMaskValidator'], 'cadefubi');
  $validatorManager->registerName('nomubi', 1, 'La Descripción no puedo estar en Blanco', 'cadefubi', null, false);
  $validatorManager->registerValidator('nomubi', $validators['MyStringValidator'], 'cadefubi');
  $context->getRequest()->setAttribute('fillin', array (
), 'symfony/filter');
}
