<?php
// auto-generated by PropelCidesa
// date: 2017/02/13 05:39:36
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<td colspan="3">
    <?php echo link_to($fatipmov->getDesmov() ? $fatipmov->getDesmov() : __('-'), 'fatipmov/edit?id='.$fatipmov->getId()) ?>
     - 
    <?php echo $fatipmov->getNomabr() ?>
     - 
    <?php echo $fatipmov->getDebcre() ?>
     - 
</td>