<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:40:56
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomdefespgen 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_codemp">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npdefgen/sort') == 'codemp'): ?>
      <?php echo link_to(__('Código Empresa'), 'nomdefespgen/list?sort=codemp&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Código Empresa'), 'nomdefespgen/list?sort=codemp&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomemp">
        <?php echo __('Nombre Empresa') ?>
          </th>
  <th id="sf_admin_list_th_forcar">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npdefgen/sort') == 'forcar'): ?>
      <?php echo link_to(__('Cargo'), 'nomdefespgen/list?sort=forcar&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Cargo'), 'nomdefespgen/list?sort=forcar&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_foremp">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npdefgen/sort') == 'foremp'): ?>
      <?php echo link_to(__('Empleado'), 'nomdefespgen/list?sort=foremp&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Empleado'), 'nomdefespgen/list?sort=foremp&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_fororg">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npdefgen/sort') == 'fororg'): ?>
      <?php echo link_to(__('Nivel Organizacional'), 'nomdefespgen/list?sort=fororg&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nivel Organizacional'), 'nomdefespgen/list?sort=fororg&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_foruni">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npdefgen/sort') == 'foruni'): ?>
      <?php echo link_to(__('Unidad Ejecutora'), 'nomdefespgen/list?sort=foruni&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npdefgen/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Unidad Ejecutora'), 'nomdefespgen/list?sort=foruni&type=asc') ?>
      <?php endif; ?>
          </th>
