<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:40:56
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomdefespgen 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<td colspan="6">
    <?php echo link_to($npdefgen->getCodemp() ? $npdefgen->getCodemp() : __('-'), 'nomdefespgen/edit?id='.$npdefgen->getId()) ?>
     - 
    <?php echo $npdefgen->getNomemp() ?>
     - 
    <?php echo $npdefgen->getForcar() ?>
     - 
    <?php echo $npdefgen->getForemp() ?>
     - 
    <?php echo $npdefgen->getFororg() ?>
     - 
    <?php echo $npdefgen->getForuni() ?>
     - 
</td>