<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:32:17
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmdefalm 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_codalm">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/cadefalm/sort') == 'codalm'): ?>
      <?php echo link_to(__('Código'), 'almdefalm/list?sort=codalm&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefalm/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefalm/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Código'), 'almdefalm/list?sort=codalm&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomalm">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/cadefalm/sort') == 'nomalm'): ?>
      <?php echo link_to(__('Descripción'), 'almdefalm/list?sort=nomalm&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefalm/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefalm/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Descripción'), 'almdefalm/list?sort=nomalm&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_codcat">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/cadefalm/sort') == 'codcat'): ?>
      <?php echo link_to(__('Cod. Unidad Asociada'), 'almdefalm/list?sort=codcat&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefalm/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefalm/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Cod. Unidad Asociada'), 'almdefalm/list?sort=codcat&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomcat">
        <?php echo __('Unidad Asociada') ?>
          </th>
