<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:45:12
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomdefespban 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<td colspan="2">
    <?php echo link_to($npbancos->getCodban() ? $npbancos->getCodban() : __('-'), 'nomdefespban/edit?id='.$npbancos->getId()) ?>
     - 
    <?php echo $npbancos->getNomban() ?>
     - 
</td>