<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:29:04
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmregart 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<td colspan="6">
    <?php echo link_to($caregart->getCodart() ? $caregart->getCodart() : __('-'), 'almregart/edit?id='.$caregart->getId()) ?>
     - 
    <?php echo $caregart->getDesart() ?>
     - 
    <?php echo $caregart->getTipo() ?>
     - 
    <?php echo $caregart->getRamart() ?>
     - 
    <?php echo $caregart->getNomram() ?>
     - 
    <?php echo $caregart->getCodalt() ?>
     - 
</td>