<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:29:04
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmregart 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: editSuccess.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Registro de Artículos ó Servicios', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('almregart/edit_header', array('caregart' => $caregart)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('almregart/edit_messages', array('caregart' => $caregart, 'labels' => $labels)) ?>
<?php include_partial('almregart/edit_form', array('caregart' => $caregart, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('almregart/edit_footer', array('caregart' => $caregart)) ?>
</div>

</div>
