<?php
// auto-generated by cidesaDefineEnvironmentConfigHandler
// date: 2017/02/13 05:32:58
sfConfig::add(array(
  'app_autenticacion' => 'autenticacion',
  'app_max_per_page' => 15,
  'app_contabilidadpresupuesto' => '/var/www/cidesa/siga_cp/',
  'app_reportes' => '/var/www/cidesa/siga_reportes/',
  'app_reportes_web' => 'reportes/reportes',
  'app_this' => 'autenticacion',
  'app_configemp' => array (
  'generales' => 
  array (
    'mostodart' => 'S',
  ),
  'aplicacion' => 
  array (
    'nomina' => 
    array (
      'modulos' => 
      array (
        'nomnomcienom' => 
        array (
          'intpre' => 'S',
        ),
      ),
    ),
    'contabilidad' => 
    array (
      'modulos' => 
      array (
        'confincom' => 
        array (
          'camnomcatcta' => 'S',
        ),
      ),
    ),
  ),
),
));
