<?php
// auto-generated by PropelCidesa
// date: 2012/05/22 17:00:00
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_footer.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>
<script type="text/javascript" language="JavaScript">
 var estado= '<?php echo $cpajuste->getStaaju() ?>';
  if (estado=='N')
 {
     $$('.sf_admin_action_delete')[0].hide();
     $$('.sf_admin_action_delete')[1].hide();
     $$('.sf_admin_action_save')[2].hide();
 }
var gencomaju='<?php echo H::getConfApp2('gencomaju', 'presupuesto', 'preajuste');?>';
if (gencomaju=='S' && ($('cpajuste_reftipaju').value=='P' ||  $('cpajuste_reftipaju').value=='C'))
    $$('.sf_admin_action_save')[1].hide();
</script>