<?php
// auto-generated by PropelCidesa
// date: 2017/02/13 06:41:29
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php echo form_tag('precongen/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($cpdefniv, 'getId') ?>

<?php
  $fields = CpdefnivPeer::getFieldNames();

  if(array_search('Codalmusu', $fields))
  {  ?>
  <h2 class="h2" onclick="javascript: return $('divusualms').toggle();"><?php echo __('Almacenes') ?></h2>
  <fieldset id="sf_fieldset_usualms" class="">
  <div class="form-row" id="divusualms">
    <?php echo label_for('cpdefniv[codalmusu]', __('Almacenes Por Usuario: '), 'class="required" Style="text-align:left; width:150px"') ?>
    <div class="content">
    <?php
      $almacenes = $sf_user->getAttribute('usualms',array());
      if(count($almacenes)>0){
        $keys = array_keys($almacenes);
        $codalm = $keys[0];
      }else $codalm = '';
      if($codalm == '') echo label_for('cpdefniv[codalmusu]', __('Usuario sin Almacen Asociado'), 'class="required" Style="text-align:left; width:150px"').'<br><br><br>';
      else echo select_tag('cpdefniv[codalmusu]',options_for_select($almacenes,$cpdefniv->getCodalmusu()!='' ? $cpdefniv->getCodalmusu() : $codalm), ( ($cpdefniv->getId()) ? 'disabled=true' : '').' style=width:500px');
    ?>
    </div>
  </div>
  </fieldset>
<?php } ?>



<h2 class="h2" onclick="javascript: return $('divCorrelativos').toggle();"><?php echo __('Correlativos') ?></h2>
<fieldset id="sf_fieldset_correlativos" class="">

<div class="form-row" id="divCorrelativos">
<div id="divcoraep">
  <?php if($labels['cpdefniv{coraep}']!='.:') { ?>
  <?php echo label_for('cpdefniv[coraep]', __($labels['cpdefniv{coraep}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{coraep}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{coraep}')): ?>
    <?php echo form_error('cpdefniv{coraep}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCoraep', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[coraep]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{coraep}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcorprc">
  <?php if($labels['cpdefniv{corprc}']!='.:') { ?>
  <?php echo label_for('cpdefniv[corprc]', __($labels['cpdefniv{corprc}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{corprc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{corprc}')): ?>
    <?php echo form_error('cpdefniv{corprc}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCorprc', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[corprc]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{corprc}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcorcom">
  <?php if($labels['cpdefniv{corcom}']!='.:') { ?>
  <?php echo label_for('cpdefniv[corcom]', __($labels['cpdefniv{corcom}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{corcom}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{corcom}')): ?>
    <?php echo form_error('cpdefniv{corcom}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCorcom', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[corcom]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{corcom}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcorcau">
  <?php if($labels['cpdefniv{corcau}']!='.:') { ?>
  <?php echo label_for('cpdefniv[corcau]', __($labels['cpdefniv{corcau}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{corcau}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{corcau}')): ?>
    <?php echo form_error('cpdefniv{corcau}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCorcau', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[corcau]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{corcau}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcorpag">
  <?php if($labels['cpdefniv{corpag}']!='.:') { ?>
  <?php echo label_for('cpdefniv[corpag]', __($labels['cpdefniv{corpag}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{corpag}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{corpag}')): ?>
    <?php echo form_error('cpdefniv{corpag}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCorpag', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[corpag]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{corpag}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcorsoltra">
  <?php if($labels['cpdefniv{corsoltra}']!='.:') { ?>
  <?php echo label_for('cpdefniv[corsoltra]', __($labels['cpdefniv{corsoltra}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{corsoltra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{corsoltra}')): ?>
    <?php echo form_error('cpdefniv{corsoltra}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCorsoltra', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[corsoltra]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{corsoltra}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcortrasla">
  <?php if($labels['cpdefniv{cortrasla}']!='.:') { ?>
  <?php echo label_for('cpdefniv[cortrasla]', __($labels['cpdefniv{cortrasla}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{cortrasla}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{cortrasla}')): ?>
    <?php echo form_error('cpdefniv{cortrasla}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCortrasla', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[cortrasla]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{cortrasla}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcorsoladidis">
  <?php if($labels['cpdefniv{corsoladidis}']!='.:') { ?>
  <?php echo label_for('cpdefniv[corsoladidis]', __($labels['cpdefniv{corsoladidis}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{corsoladidis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{corsoladidis}')): ?>
    <?php echo form_error('cpdefniv{corsoladidis}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCorsoladidis', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[corsoladidis]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{corsoladidis}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcoradidis">
  <?php if($labels['cpdefniv{coradidis}']!='.:') { ?>
  <?php echo label_for('cpdefniv[coradidis]', __($labels['cpdefniv{coradidis}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{coradidis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{coradidis}')): ?>
    <?php echo form_error('cpdefniv{coradidis}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCoradidis', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[coradidis]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{coradidis}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcoraju">
  <?php if($labels['cpdefniv{coraju}']!='.:') { ?>
  <?php echo label_for('cpdefniv[coraju]', __($labels['cpdefniv{coraju}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{coraju}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{coraju}')): ?>
    <?php echo form_error('cpdefniv{coraju}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($cpdefniv, 'getCoraju', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'cpdefniv[coraju]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{coraju}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divGenerales').toggle();"><?php echo __('Generales') ?></h2>
<fieldset id="sf_fieldset_generales" class="">

<div class="form-row" id="divGenerales">
<div id="divbtnanu">
  <?php if($labels['cpdefniv{btnanu}']!='.:') { ?>
  <?php echo label_for('cpdefniv[btnanu]', __($labels['cpdefniv{btnanu}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{btnanu}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{btnanu}')): ?>
    <?php echo form_error('cpdefniv{btnanu}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($cpdefniv, 'getBtnanu', array (
  'control_name' => 'cpdefniv[btnanu]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{btnanu}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divbtneli">
  <?php if($labels['cpdefniv{btneli}']!='.:') { ?>
  <?php echo label_for('cpdefniv[btneli]', __($labels['cpdefniv{btneli}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{btneli}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{btneli}')): ?>
    <?php echo form_error('cpdefniv{btneli}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($cpdefniv, 'getBtneli', array (
  'control_name' => 'cpdefniv[btneli]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{btneli}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divconpar">
  <?php if($labels['cpdefniv{conpar}']!='.:') { ?>
  <?php echo label_for('cpdefniv[conpar]', __($labels['cpdefniv{conpar}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{conpar}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{conpar}')): ?>
    <?php echo form_error('cpdefniv{conpar}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('conpar', array('type' => 'edit', 'cpdefniv' => $cpdefniv,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['cpdefniv{conpar}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divDatos Compromiso de Nómina').toggle();"><?php echo __('Datos Compromiso de Nómina') ?></h2>
<fieldset id="sf_fieldset_datos_compromiso_de_n__mina" class="">

<div class="form-row" id="divDatos Compromiso de Nómina">
<div id="divtipcom">
  <?php if($labels['cpdefniv{tipcom}']!='.:') { ?>
  <?php echo label_for('cpdefniv[tipcom]', __($labels['cpdefniv{tipcom}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{tipcom}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{tipcom}')): ?>
    <?php echo form_error('cpdefniv{tipcom}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($cpdefniv, 1, array (
  'getprincipal' => 'getTipcom',
  'getsecundario' => 'getNomdoc',
  'campoprincipal' => 'tipcom',
  'camposecundario' => 'nomdoc',
  'campobase' => 'id',
),  'Precompro_Cpdoccom',  'Cpdoccom',  '',  '',  '');?>

  	
  <?php if($labels['cpdefniv{tipcom}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcedrif">
  <?php if($labels['cpdefniv{cedrif}']!='.:') { ?>
  <?php echo label_for('cpdefniv[cedrif]', __($labels['cpdefniv{cedrif}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('cpdefniv{cedrif}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('cpdefniv{cedrif}')): ?>
    <?php echo form_error('cpdefniv{cedrif}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($cpdefniv, 2, array (
  'getprincipal' => 'getCedrif',
  'getsecundario' => 'getNomben',
  'campoprincipal' => 'cedrif',
  'camposecundario' => 'nomben',
  'campobase' => 'id',
),  'Preprecom_Opbenefi',  'Opbenefi',  '',  '',  '');?>

  	
  <?php if($labels['cpdefniv{cedrif}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<?php include_partial('edit_actions', array('cpdefniv' => $cpdefniv)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>

