<?php
// auto-generated by PropelCidesa
// date: 2017/02/17 10:36:44
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_tabular.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

    <td><?php echo link_to($cadefalm->getCodalm() ? $cadefalm->getCodalm() : __('-'), 'fadefalm/edit?id='.$cadefalm->getId()) ?></td>
    <td><?php echo $cadefalm->getNomalm() ?></td>
      <td><?php echo $cadefalm->getCodcat() ?></td>
      <td><?php echo $cadefalm->getNomcat() ?></td>
  