<?php
// auto-generated by PropelCidesa
// date: 2017/02/13 05:33:06
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php echo form_tag('fafactur/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($fafactur, 'getId') ?>

<?php
  $fields = FafacturPeer::getFieldNames();

  if(array_search('Codalmusu', $fields))
  {  ?>
  <h2 class="h2" onclick="javascript: return $('divusualms').toggle();"><?php echo __('Almacenes') ?></h2>
  <fieldset id="sf_fieldset_usualms" class="">
  <div class="form-row" id="divusualms">
    <?php echo label_for('fafactur[codalmusu]', __('Almacenes Por Usuario: '), 'class="required" Style="text-align:left; width:150px"') ?>
    <div class="content">
    <?php
      $almacenes = $sf_user->getAttribute('usualms',array());
      if(count($almacenes)>0){
        $keys = array_keys($almacenes);
        $codalm = $keys[0];
      }else $codalm = '';
      if($codalm == '') echo label_for('fafactur[codalmusu]', __('Usuario sin Almacen Asociado'), 'class="required" Style="text-align:left; width:150px"').'<br><br><br>';
      else echo select_tag('fafactur[codalmusu]',options_for_select($almacenes,$fafactur->getCodalmusu()!='' ? $fafactur->getCodalmusu() : $codalm), ( ($fafactur->getId()) ? 'disabled=true' : '').' style=width:500px');
    ?>
    </div>
  </div>
  </fieldset>
<?php } ?>

<?php echo object_input_hidden_tag($fafactur, 'getCodcli', array('id' => 'fafactur_codcli', 'name' => 'fafactur[codcli]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getReapor', array('id' => 'fafactur_reapor', 'name' => 'fafactur[reapor]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getStatus', array('id' => 'fafactur_status', 'name' => 'fafactur[status]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getValmon', array('id' => 'fafactur_valmon', 'name' => 'fafactur[valmon]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getNumcom', array('id' => 'fafactur_numcom', 'name' => 'fafactur[numcom]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getNumcomord', array('id' => 'fafactur_numcomord', 'name' => 'fafactur[numcomord]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getNumcominv', array('id' => 'fafactur_numcominv', 'name' => 'fafactur[numcominv]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getIncluircliente', array('id' => 'fafactur_incluircliente', 'name' => 'fafactur[incluircliente]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTipconpag', array('id' => 'fafactur_tipconpag', 'name' => 'fafactur[tipconpag]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTipo', array('id' => 'fafactur_tipo', 'name' => 'fafactur[tipo]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getApliclades', array('id' => 'fafactur_apliclades', 'name' => 'fafactur[apliclades]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getDocrefiera', array('id' => 'fafactur_docrefiera', 'name' => 'fafactur[docrefiera]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getEsretencion', array('id' => 'fafactur_esretencion', 'name' => 'fafactur[esretencion]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTottotart', array('id' => 'fafactur_tottotart', 'name' => 'fafactur[tottotart]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTotmonrgo', array('id' => 'fafactur_totmonrgo', 'name' => 'fafactur[totmonrgo]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getMonedaanterior', array('id' => 'fafactur_monedaanterior', 'name' => 'fafactur[monedaanterior]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTrajo', array('id' => 'fafactur_trajo', 'name' => 'fafactur[trajo]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getPorcentajedescto', array('id' => 'fafactur_porcentajedescto', 'name' => 'fafactur[porcentajedescto]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTotcanpreart', array('id' => 'fafactur_totcanpreart', 'name' => 'fafactur[totcanpreart]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTotprecio', array('id' => 'fafactur_totprecio', 'name' => 'fafactur[totprecio]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getCtasociada', array('id' => 'fafactur_ctasociada', 'name' => 'fafactur[ctasociada]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getCtacli', array('id' => 'fafactur_ctacli', 'name' => 'fafactur[ctacli]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getFilgenmov', array('id' => 'fafactur_filgenmov', 'name' => 'fafactur[filgenmov]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getLimitecredito', array('id' => 'fafactur_limitecredito', 'name' => 'fafactur[limitecredito]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getMancatdes', array('id' => 'fafactur_mancatdes', 'name' => 'fafactur[mancatdes]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getCodcenaco', array('id' => 'fafactur_codcenaco', 'name' => 'fafactur[codcenaco]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getNumfilas', array('id' => 'fafactur_numfilas', 'name' => 'fafactur[numfilas]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getFilactrec', array('id' => 'fafactur_filactrec', 'name' => 'fafactur[filactrec]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getFilactdes', array('id' => 'fafactur_filactdes', 'name' => 'fafactur[filactdes]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getFadescripfacId', array('id' => 'fafactur_fadescripfac_id', 'name' => 'fafactur[fadescripfac_id]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getTierecar', array('id' => 'fafactur_tierecar', 'name' => 'fafactur[tierecar]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getManporped', array('id' => 'fafactur_manporped', 'name' => 'fafactur[manporped]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getCodalmcaj', array('id' => 'fafactur_codalmcaj', 'name' => 'fafactur[codalmcaj]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getEsprecon', array('id' => 'fafactur_esprecon', 'name' => 'fafactur[esprecon]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getManprecon', array('id' => 'fafactur_manprecon', 'name' => 'fafactur[manprecon]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getNompro', array('id' => 'fafactur_nompro', 'name' => 'fafactur[nompro]')) ?>
<?php echo object_input_hidden_tag($fafactur, 'getCalrecdes', array('id' => 'fafactur_calrecdes', 'name' => 'fafactur[calrecdes]')) ?>


<h2 class="h2" onclick="javascript: return $('divDatos de la Factura').toggle();"><?php echo __('Datos de la Factura') ?></h2>
<fieldset id="sf_fieldset_datos_de_la_factura" class="">

<div class="form-row" id="divDatos de la Factura">
<div id="divbtnprint">
  <?php if($labels['fafactur{btnprint}']!='.:') { ?>
  <?php echo label_for('fafactur[btnprint]', __($labels['fafactur{btnprint}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{btnprint}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{btnprint}')): ?>
    <?php echo form_error('fafactur{btnprint}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('btnprint', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{btnprint}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcaj">
  <?php if($labels['fafactur{codcaj}']!='.:') { ?>
  <?php echo label_for('fafactur[codcaj]', __($labels['fafactur{codcaj}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codcaj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codcaj}')): ?>
    <?php echo form_error('fafactur{codcaj}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getCodcaj', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'fafactur[codcaj]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{codcaj}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divreffac">
  <?php if($labels['fafactur{reffac}']!='.:') { ?>
  <?php echo label_for('fafactur[reffac]', __($labels['fafactur{reffac}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{reffac}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{reffac}')): ?>
    <?php echo form_error('fafactur{reffac}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getReffac', array (
  'size' => 20,
  'control_name' => 'fafactur[reffac]',
  'maxlength' => 8,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{reffac}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecfac">
  <?php if($labels['fafactur{fecfac}']!='.:') { ?>
  <?php echo label_for('fafactur[fecfac]', __($labels['fafactur{fecfac}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fecfac}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fecfac}')): ?>
    <?php echo form_error('fafactur{fecfac}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFecfac', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fecfac]',
  'date_format' => 'dd/MM/yyyy',
  'size' => 10,
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fecfac}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtipref">
  <?php if($labels['fafactur{tipref}']!='.:') { ?>
  <?php echo label_for('fafactur[tipref]', __($labels['fafactur{tipref}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{tipref}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{tipref}')): ?>
    <?php echo form_error('fafactur{tipref}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('tipref', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{tipref}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtipmon">
  <?php if($labels['fafactur{tipmon}']!='.:') { ?>
  <?php echo label_for('fafactur[tipmon]', __($labels['fafactur{tipmon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{tipmon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{tipmon}')): ?>
    <?php echo form_error('fafactur{tipmon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('tipmon', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{tipmon}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divrifpro">
  <?php if($labels['fafactur{rifpro}']!='.:') { ?>
  <?php echo label_for('fafactur[rifpro]', __($labels['fafactur{rifpro}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{rifpro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{rifpro}')): ?>
    <?php echo form_error('fafactur{rifpro}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('rifpro', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{rifpro}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtelpro">
  <?php if($labels['fafactur{telpro}']!='.:') { ?>
  <?php echo label_for('fafactur[telpro]', __($labels['fafactur{telpro}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{telpro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{telpro}')): ?>
    <?php echo form_error('fafactur{telpro}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getTelpro', array (
  'disabled' => true,
  'control_name' => 'fafactur[telpro]',
  'readonly' => true,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{telpro}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divdirpro">
  <?php if($labels['fafactur{dirpro}']!='.:') { ?>
  <?php echo label_for('fafactur[dirpro]', __($labels['fafactur{dirpro}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{dirpro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{dirpro}')): ?>
    <?php echo form_error('fafactur{dirpro}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getDirpro', array (
  'disabled' => true,
  'control_name' => 'fafactur[dirpro]',
  'readonly' => true,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{dirpro}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtipper">
  <?php if($labels['fafactur{tipper}']!='.:') { ?>
  <?php echo label_for('fafactur[tipper]', __($labels['fafactur{tipper}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{tipper}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{tipper}')): ?>
    <?php echo form_error('fafactur{tipper}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getTipper', array (
  'disabled' => true,
  'control_name' => 'fafactur[tipper]',
  'readonly' => true,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{tipper}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodconpag">
  <?php if($labels['fafactur{codconpag}']!='.:') { ?>
  <?php echo label_for('fafactur[codconpag]', __($labels['fafactur{codconpag}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codconpag}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codconpag}')): ?>
    <?php echo form_error('fafactur{codconpag}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codconpag', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{codconpag}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcon">
  <?php if($labels['fafactur{codcon}']!='.:') { ?>
  <?php echo label_for('fafactur[codcon]', __($labels['fafactur{codcon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codcon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codcon}')): ?>
    <?php echo form_error('fafactur{codcon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codcon', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{codcon}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divdesfac">
  <?php if($labels['fafactur{desfac}']!='.:') { ?>
  <?php echo label_for('fafactur[desfac]', __($labels['fafactur{desfac}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{desfac}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{desfac}')): ?>
    <?php echo form_error('fafactur{desfac}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getDesfac', array (
  'size' => 80,
  'control_name' => 'fafactur[desfac]',
  'maxlength' => 255,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{desfac}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmonto">
  <?php if($labels['fafactur{monto}']!='.:') { ?>
  <?php echo label_for('fafactur[monto]', __($labels['fafactur{monto}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{monto}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{monto}')): ?>
    <?php echo form_error('fafactur{monto}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getMonto', array (
  'disabled' => true,
  'control_name' => 'fafactur[monto]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{monto}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmonrgo">
  <?php if($labels['fafactur{monrgo}']!='.:') { ?>
  <?php echo label_for('fafactur[monrgo]', __($labels['fafactur{monrgo}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{monrgo}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{monrgo}')): ?>
    <?php echo form_error('fafactur{monrgo}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getMonrgo', array (
  'disabled' => true,
  'control_name' => 'fafactur[monrgo]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{monrgo}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmondesc">
  <?php if($labels['fafactur{mondesc}']!='.:') { ?>
  <?php echo label_for('fafactur[mondesc]', __($labels['fafactur{mondesc}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{mondesc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{mondesc}')): ?>
    <?php echo form_error('fafactur{mondesc}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, array('getMondesc',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fafactur[mondesc]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{mondesc}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmonfac">
  <?php if($labels['fafactur{monfac}']!='.:') { ?>
  <?php echo label_for('fafactur[monfac]', __($labels['fafactur{monfac}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{monfac}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{monfac}')): ?>
    <?php echo form_error('fafactur{monfac}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, array('getMonfac',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fafactur[monfac]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{monfac}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcombo">
  <?php if($labels['fafactur{combo}']!='.:') { ?>
  <?php echo label_for('fafactur[combo]', __($labels['fafactur{combo}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{combo}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{combo}')): ?>
    <?php echo form_error('fafactur{combo}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getCombo', array (
  'disabled' => true,
  'control_name' => 'fafactur[combo]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{combo}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divrefproform">
  <?php if($labels['fafactur{refproform}']!='.:') { ?>
  <?php echo label_for('fafactur[refproform]', __($labels['fafactur{refproform}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{refproform}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{refproform}')): ?>
    <?php echo form_error('fafactur{refproform}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getRefproform', array (
  'disabled' => true,
  'control_name' => 'fafactur[refproform]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{refproform}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divproform">
  <?php if($labels['fafactur{proform}']!='.:') { ?>
  <?php echo label_for('fafactur[proform]', __($labels['fafactur{proform}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{proform}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{proform}')): ?>
    <?php echo form_error('fafactur{proform}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getProform', array (
  'size' => 20,
  'control_name' => 'fafactur[proform]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{proform}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumcontrol">
  <?php if($labels['fafactur{numcontrol}']!='.:') { ?>
  <?php echo label_for('fafactur[numcontrol]', __($labels['fafactur{numcontrol}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{numcontrol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{numcontrol}')): ?>
    <?php echo form_error('fafactur{numcontrol}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getNumcontrol', array (
  'size' => 20,
  'control_name' => 'fafactur[numcontrol]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{numcontrol}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmarrec">
  <?php if($labels['fafactur{marrec}']!='.:') { ?>
  <?php echo label_for('fafactur[marrec]', __($labels['fafactur{marrec}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{marrec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{marrec}')): ?>
    <?php echo form_error('fafactur{marrec}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getMarrec', array (
  'disabled' => true,
  'control_name' => 'fafactur[marrec]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{marrec}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divdesrec">
  <?php if($labels['fafactur{desrec}']!='.:') { ?>
  <?php echo label_for('fafactur[desrec]', __($labels['fafactur{desrec}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{desrec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{desrec}')): ?>
    <?php echo form_error('fafactur{desrec}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getDesrec', array (
  'disabled' => true,
  'control_name' => 'fafactur[desrec]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{desrec}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodubi">
  <?php if($labels['fafactur{codubi}']!='.:') { ?>
  <?php echo label_for('fafactur[codubi]', __($labels['fafactur{codubi}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codubi}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codubi}')): ?>
    <?php echo form_error('fafactur{codubi}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getCodubi', array (
  'size' => 30,
  'control_name' => 'fafactur[codubi]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{codubi}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtipoven">
  <?php if($labels['fafactur{tipoven}']!='.:') { ?>
  <?php echo label_for('fafactur[tipoven]', __($labels['fafactur{tipoven}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{tipoven}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{tipoven}')): ?>
    <?php echo form_error('fafactur{tipoven}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getTipoven', array (
  'size' => 20,
  'control_name' => 'fafactur[tipoven]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{tipoven}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divdescli">
  <?php if($labels['fafactur{descli}']!='.:') { ?>
  <?php echo label_for('fafactur[descli]', __($labels['fafactur{descli}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{descli}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{descli}')): ?>
    <?php echo form_error('fafactur{descli}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getDescli', array (
  'disabled' => true,
  'control_name' => 'fafactur[descli]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{descli}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divajucal">
  <?php if($labels['fafactur{ajucal}']!='.:') { ?>
  <?php echo label_for('fafactur[ajucal]', __($labels['fafactur{ajucal}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{ajucal}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{ajucal}')): ?>
    <?php echo form_error('fafactur{ajucal}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getAjucal', array (
  'disabled' => true,
  'control_name' => 'fafactur[ajucal]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{ajucal}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divbtufin">
  <?php if($labels['fafactur{btufin}']!='.:') { ?>
  <?php echo label_for('fafactur[btufin]', __($labels['fafactur{btufin}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{btufin}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{btufin}')): ?>
    <?php echo form_error('fafactur{btufin}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, array('getBtufin',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fafactur[btufin]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{btufin}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divpuedph">
  <?php if($labels['fafactur{puedph}']!='.:') { ?>
  <?php echo label_for('fafactur[puedph]', __($labels['fafactur{puedph}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{puedph}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{puedph}')): ?>
    <?php echo form_error('fafactur{puedph}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getPuedph', array (
  'size' => 25,
  'control_name' => 'fafactur[puedph]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{puedph}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divpuedes">
  <?php if($labels['fafactur{puedes}']!='.:') { ?>
  <?php echo label_for('fafactur[puedes]', __($labels['fafactur{puedes}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{puedes}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{puedes}')): ?>
    <?php echo form_error('fafactur{puedes}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getPuedes', array (
  'size' => 25,
  'control_name' => 'fafactur[puedes]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{puedes}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divbuque">
  <?php if($labels['fafactur{buque}']!='.:') { ?>
  <?php echo label_for('fafactur[buque]', __($labels['fafactur{buque}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{buque}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{buque}')): ?>
    <?php echo form_error('fafactur{buque}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getBuque', array (
  'size' => 50,
  'control_name' => 'fafactur[buque]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{buque}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodalm">
  <?php if($labels['fafactur{codalm}']!='.:') { ?>
  <?php echo label_for('fafactur[codalm]', __($labels['fafactur{codalm}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codalm}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codalm}')): ?>
    <?php echo form_error('fafactur{codalm}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getCodalm', array (
  'disabled' => true,
  'control_name' => 'fafactur[codalm]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{codalm}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divporped">
  <?php if($labels['fafactur{porped}']!='.:') { ?>
  <?php echo label_for('fafactur[porped]', __($labels['fafactur{porped}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{porped}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{porped}')): ?>
    <?php echo form_error('fafactur{porped}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getPorped', array (
  'disabled' => true,
  'control_name' => 'fafactur[porped]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{porped}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcoddirec">
  <?php if($labels['fafactur{coddirec}']!='.:') { ?>
  <?php echo label_for('fafactur[coddirec]', __($labels['fafactur{coddirec}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{coddirec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{coddirec}')): ?>
    <?php echo form_error('fafactur{coddirec}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($fafactur, 42, array (
  'getprincipal' => 'getCoddirec',
  'getsecundario' => 'getDesdirec',
  'campoprincipal' => 'coddirec',
  'camposecundario' => 'desdirec',
  'campobase' => 'id',
),  'Cadefdirec_Almdefdiv',  'Cadefdirec',  '',  '',  '');?>

  	
  <?php if($labels['fafactur{coddirec}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divDetalle').toggle();"><?php echo __('Detalle') ?></h2>
<fieldset id="sf_fieldset_detalle" class="">

<div class="form-row" id="divDetalle">
<div id="divlistaart">
  <?php if($labels['fafactur{listaart}']!='.:') { ?>
  <?php echo label_for('fafactur[listaart]', __($labels['fafactur{listaart}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{listaart}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{listaart}')): ?>
    <?php echo form_error('fafactur{listaart}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getListaart', array (
  'disabled' => true,
  'control_name' => 'fafactur[listaart]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{listaart}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgrid_fapeddes">
  <?php if($labels['fafactur{grid_fapeddes}']!='.:') { ?>
  <?php echo label_for('fafactur[grid_fapeddes]', __($labels['fafactur{grid_fapeddes}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{grid_fapeddes}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{grid_fapeddes}')): ?>
    <?php echo form_error('fafactur{grid_fapeddes}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('grid_fapeddes', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{grid_fapeddes}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgrid_faartfac">
  <?php if($labels['fafactur{grid_faartfac}']!='.:') { ?>
  <?php echo label_for('fafactur[grid_faartfac]', __($labels['fafactur{grid_faartfac}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{grid_faartfac}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{grid_faartfac}')): ?>
    <?php echo form_error('fafactur{grid_faartfac}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('grid_faartfac', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{grid_faartfac}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgrid_fadescart">
  <?php if($labels['fafactur{grid_fadescart}']!='.:') { ?>
  <?php echo label_for('fafactur[grid_fadescart]', __($labels['fafactur{grid_fadescart}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{grid_fadescart}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{grid_fadescart}')): ?>
    <?php echo form_error('fafactur{grid_fadescart}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('grid_fadescart', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{grid_fadescart}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtotdesc">
  <?php if($labels['fafactur{totdesc}']!='.:') { ?>
  <?php echo label_for('fafactur[totdesc]', __($labels['fafactur{totdesc}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{totdesc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{totdesc}')): ?>
    <?php echo form_error('fafactur{totdesc}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getTotdesc', array (
  'disabled' => true,
  'control_name' => 'fafactur[totdesc]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{totdesc}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgrid_fargoart">
  <?php if($labels['fafactur{grid_fargoart}']!='.:') { ?>
  <?php echo label_for('fafactur[grid_fargoart]', __($labels['fafactur{grid_fargoart}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{grid_fargoart}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{grid_fargoart}')): ?>
    <?php echo form_error('fafactur{grid_fargoart}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('grid_fargoart', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{grid_fargoart}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtotrec">
  <?php if($labels['fafactur{totrec}']!='.:') { ?>
  <?php echo label_for('fafactur[totrec]', __($labels['fafactur{totrec}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{totrec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{totrec}')): ?>
    <?php echo form_error('fafactur{totrec}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getTotrec', array (
  'disabled' => true,
  'control_name' => 'fafactur[totrec]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{totrec}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgrid_fafaclib">
  <?php if($labels['fafactur{grid_fafaclib}']!='.:') { ?>
  <?php echo label_for('fafactur[grid_fafaclib]', __($labels['fafactur{grid_fafaclib}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{grid_fafaclib}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{grid_fafaclib}')): ?>
    <?php echo form_error('fafactur{grid_fafaclib}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('grid_fafaclib', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{grid_fafaclib}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divForma de Pago').toggle();"><?php echo __('Forma de Pago') ?></h2>
<fieldset id="sf_fieldset_forma_de_pago" class="">

<div class="form-row" id="divForma de Pago">
<div id="divcodtip">
  <?php if($labels['fafactur{codtip}']!='.:') { ?>
  <?php echo label_for('fafactur[codtip]', __($labels['fafactur{codtip}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codtip}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codtip}')): ?>
    <?php echo form_error('fafactur{codtip}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codtip', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{codtip}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgrid_faforpag">
  <?php if($labels['fafactur{grid_faforpag}']!='.:') { ?>
  <?php echo label_for('fafactur[grid_faforpag]', __($labels['fafactur{grid_faforpag}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{grid_faforpag}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{grid_faforpag}')): ?>
    <?php echo form_error('fafactur{grid_faforpag}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('grid_faforpag', array('type' => 'edit', 'fafactur' => $fafactur,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{grid_faforpag}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmoncan">
  <?php if($labels['fafactur{moncan}']!='.:') { ?>
  <?php echo label_for('fafactur[moncan]', __($labels['fafactur{moncan}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{moncan}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{moncan}')): ?>
    <?php echo form_error('fafactur{moncan}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getMoncan', array (
  'disabled' => true,
  'control_name' => 'fafactur[moncan]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{moncan}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmonres">
  <?php if($labels['fafactur{monres}']!='.:') { ?>
  <?php echo label_for('fafactur[monres]', __($labels['fafactur{monres}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{monres}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{monres}')): ?>
    <?php echo form_error('fafactur{monres}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getMonres', array (
  'disabled' => true,
  'control_name' => 'fafactur[monres]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{monres}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divvuelto">
  <?php if($labels['fafactur{vuelto}']!='.:') { ?>
  <?php echo label_for('fafactur[vuelto]', __($labels['fafactur{vuelto}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{vuelto}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{vuelto}')): ?>
    <?php echo form_error('fafactur{vuelto}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, array('getVuelto',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fafactur[vuelto]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{vuelto}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divDescripción Detallada/Sucursal').toggle();"><?php echo __('Descripción Detallada/Sucursal') ?></h2>
<fieldset id="sf_fieldset_descripci__n_detallada_sucursal" class="">

<div class="form-row" id="divDescripción Detallada/Sucursal">
<div id="divobserv">
  <?php if($labels['fafactur{observ}']!='.:') { ?>
  <?php echo label_for('fafactur[observ]', __($labels['fafactur{observ}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{observ}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{observ}')): ?>
    <?php echo form_error('fafactur{observ}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($fafactur, 'getObserv', array (
  'control_name' => 'fafactur[observ]',
  'size' => '80x5',
  'maxlength' => 500,
  'onkeyup' => 'return ismaxlength(this)',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{observ}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divsucursal">
  <?php if($labels['fafactur{sucursal}']!='.:') { ?>
  <?php echo label_for('fafactur[sucursal]', __($labels['fafactur{sucursal}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{sucursal}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{sucursal}')): ?>
    <?php echo form_error('fafactur{sucursal}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getSucursal', array (
  'size' => 50,
  'control_name' => 'fafactur[sucursal]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{sucursal}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divusuarios">
  <?php if($labels['fafactur{usuarios}']!='.:') { ?>
  <?php echo label_for('fafactur[usuarios]', __($labels['fafactur{usuarios}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{usuarios}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{usuarios}')): ?>
    <?php echo form_error('fafactur{usuarios}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getUsuarios', array (
  'disabled' => true,
  'control_name' => 'fafactur[usuarios]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{usuarios}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divpassword">
  <?php if($labels['fafactur{password}']!='.:') { ?>
  <?php echo label_for('fafactur[password]', __($labels['fafactur{password}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{password}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{password}')): ?>
    <?php echo form_error('fafactur{password}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getPassword', array (
  'disabled' => true,
  'control_name' => 'fafactur[password]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{password}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divobsfac">
  <?php if($labels['fafactur{obsfac}']!='.:') { ?>
  <?php echo label_for('fafactur[obsfac]', __($labels['fafactur{obsfac}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{obsfac}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{obsfac}')): ?>
    <?php echo form_error('fafactur{obsfac}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getObsfac', array (
  'size' => 80,
  'control_name' => 'fafactur[obsfac]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{obsfac}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divOtros Datos').toggle();"><?php echo __('Otros Datos') ?></h2>
<fieldset id="sf_fieldset_otros_datos" class="">

<div class="form-row" id="divOtros Datos">
<div id="divnroordfac">
  <?php if($labels['fafactur{nroordfac}']!='.:') { ?>
  <?php echo label_for('fafactur[nroordfac]', __($labels['fafactur{nroordfac}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{nroordfac}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{nroordfac}')): ?>
    <?php echo form_error('fafactur{nroordfac}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getNroordfac', array (
  'size' => 20,
  'control_name' => 'fafactur[nroordfac]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{nroordfac}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodpropat">
  <?php if($labels['fafactur{codpropat}']!='.:') { ?>
  <?php echo label_for('fafactur[codpropat]', __($labels['fafactur{codpropat}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codpropat}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codpropat}')): ?>
    <?php echo form_error('fafactur{codpropat}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($fafactur, 38, array (
  'getprincipal' => 'getCodpropat',
  'getsecundario' => 'getDespropat',
  'campoprincipal' => 'codpropat',
  'camposecundario' => 'despropat',
  'campobase' => 'id',
),  'Fapropat_Fafactur',  'Fapropat',  '',  '',  '');?>

  	
  <?php if($labels['fafactur{codpropat}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodprorad">
  <?php if($labels['fafactur{codprorad}']!='.:') { ?>
  <?php echo label_for('fafactur[codprorad]', __($labels['fafactur{codprorad}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codprorad}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codprorad}')): ?>
    <?php echo form_error('fafactur{codprorad}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($fafactur, 39, array (
  'getprincipal' => 'getCodprorad',
  'getsecundario' => 'getDesprorad',
  'campoprincipal' => 'codprorad',
  'camposecundario' => 'desprorad',
  'campobase' => 'id',
),  'Faprorad_Fafactur',  'Faprorad',  '',  '',  '');?>

  	
  <?php if($labels['fafactur{codprorad}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divversion">
  <?php if($labels['fafactur{version}']!='.:') { ?>
  <?php echo label_for('fafactur[version]', __($labels['fafactur{version}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{version}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{version}')): ?>
    <?php echo form_error('fafactur{version}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getVersion', array (
  'size' => 20,
  'control_name' => 'fafactur[version]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{version}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfectrades">
  <?php if($labels['fafactur{fectrades}']!='.:') { ?>
  <?php echo label_for('fafactur[fectrades]', __($labels['fafactur{fectrades}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fectrades}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fectrades}')): ?>
    <?php echo form_error('fafactur{fectrades}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFectrades', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fectrades]',
  'date_format' => 'dd/MM/yyyy',
  'size' => 10,
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fectrades}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfectrahas">
  <?php if($labels['fafactur{fectrahas}']!='.:') { ?>
  <?php echo label_for('fafactur[fectrahas]', __($labels['fafactur{fectrahas}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fectrahas}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fectrahas}')): ?>
    <?php echo form_error('fafactur{fectrahas}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFectrahas', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fectrahas]',
  'date_format' => 'dd/MM/yyyy',
  'size' => 10,
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fectrahas}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfrectra">
  <?php if($labels['fafactur{frectra}']!='.:') { ?>
  <?php echo label_for('fafactur[frectra]', __($labels['fafactur{frectra}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{frectra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{frectra}')): ?>
    <?php echo form_error('fafactur{frectra}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getFrectra', array (
  'size' => 20,
  'control_name' => 'fafactur[frectra]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{frectra}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divduracion">
  <?php if($labels['fafactur{duracion}']!='.:') { ?>
  <?php echo label_for('fafactur[duracion]', __($labels['fafactur{duracion}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{duracion}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{duracion}')): ?>
    <?php echo form_error('fafactur{duracion}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getDuracion', array (
  'size' => 20,
  'control_name' => 'fafactur[duracion]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{duracion}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divobstra">
  <?php if($labels['fafactur{obstra}']!='.:') { ?>
  <?php echo label_for('fafactur[obstra]', __($labels['fafactur{obstra}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{obstra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{obstra}')): ?>
    <?php echo form_error('fafactur{obstra}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getObstra', array (
  'size' => 80,
  'control_name' => 'fafactur[obstra]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{obstra}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecper1">
  <?php if($labels['fafactur{fecper1}']!='.:') { ?>
  <?php echo label_for('fafactur[fecper1]', __($labels['fafactur{fecper1}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fecper1}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fecper1}')): ?>
    <?php echo form_error('fafactur{fecper1}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFecper1', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fecper1]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fecper1}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecper2">
  <?php if($labels['fafactur{fecper2}']!='.:') { ?>
  <?php echo label_for('fafactur[fecper2]', __($labels['fafactur{fecper2}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fecper2}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fecper2}')): ?>
    <?php echo form_error('fafactur{fecper2}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFecper2', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fecper2]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fecper2}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divDatos Adicionales').toggle();"><?php echo __('Datos Adicionales') ?></h2>
<fieldset id="sf_fieldset_datos_adicionales" class="">

<div class="form-row" id="divDatos Adicionales">
<div id="divmuelle">
  <?php if($labels['fafactur{muelle}']!='.:') { ?>
  <?php echo label_for('fafactur[muelle]', __($labels['fafactur{muelle}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{muelle}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{muelle}')): ?>
    <?php echo form_error('fafactur{muelle}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getMuelle', array (
  'size' => 80,
  'control_name' => 'fafactur[muelle]',
  'maxlength' => 100,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{muelle}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divbuque2">
  <?php if($labels['fafactur{buque2}']!='.:') { ?>
  <?php echo label_for('fafactur[buque2]', __($labels['fafactur{buque2}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{buque2}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{buque2}')): ?>
    <?php echo form_error('fafactur{buque2}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getBuque2', array (
  'size' => 80,
  'control_name' => 'fafactur[buque2]',
  'maxlength' => 250,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{buque2}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divexpedi">
  <?php if($labels['fafactur{expedi}']!='.:') { ?>
  <?php echo label_for('fafactur[expedi]', __($labels['fafactur{expedi}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{expedi}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{expedi}')): ?>
    <?php echo form_error('fafactur{expedi}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getExpedi', array (
  'size' => 50,
  'control_name' => 'fafactur[expedi]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{expedi}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divbele">
  <?php if($labels['fafactur{bele}']!='.:') { ?>
  <?php echo label_for('fafactur[bele]', __($labels['fafactur{bele}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{bele}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{bele}')): ?>
    <?php echo form_error('fafactur{bele}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getBele', array (
  'size' => 80,
  'control_name' => 'fafactur[bele]',
  'maxlength' => 100,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{bele}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfactura">
  <?php if($labels['fafactur{factura}']!='.:') { ?>
  <?php echo label_for('fafactur[factura]', __($labels['fafactur{factura}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{factura}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{factura}')): ?>
    <?php echo form_error('fafactur{factura}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getFactura', array (
  'size' => 50,
  'control_name' => 'fafactur[factura]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{factura}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divembarca">
  <?php if($labels['fafactur{embarca}']!='.:') { ?>
  <?php echo label_for('fafactur[embarca]', __($labels['fafactur{embarca}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{embarca}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{embarca}')): ?>
    <?php echo form_error('fafactur{embarca}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getEmbarca', array (
  'size' => 80,
  'control_name' => 'fafactur[embarca]',
  'maxlength' => 250,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{embarca}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divdescarga">
  <?php if($labels['fafactur{descarga}']!='.:') { ?>
  <?php echo label_for('fafactur[descarga]', __($labels['fafactur{descarga}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{descarga}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{descarga}')): ?>
    <?php echo form_error('fafactur{descarga}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, 'getDescarga', array (
  'size' => 80,
  'control_name' => 'fafactur[descarga]',
  'maxlength' => 250,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{descarga}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcanbul">
  <?php if($labels['fafactur{canbul}']!='.:') { ?>
  <?php echo label_for('fafactur[canbul]', __($labels['fafactur{canbul}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{canbul}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{canbul}')): ?>
    <?php echo form_error('fafactur{canbul}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, array('getCanbul',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fafactur[canbul]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{canbul}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodprod">
  <?php if($labels['fafactur{codprod}']!='.:') { ?>
  <?php echo label_for('fafactur[codprod]', __($labels['fafactur{codprod}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{codprod}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{codprod}')): ?>
    <?php echo form_error('fafactur{codprod}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($fafactur, 41, array (
  'getprincipal' => 'getCodprod',
  'getsecundario' => 'getDesprod',
  'campoprincipal' => 'codprod',
  'camposecundario' => 'desprod',
  'campobase' => 'id',
),  'Fadefpro_Fafacturpro',  'Fadefpro',  '',  '',  '');?>

  	
  <?php if($labels['fafactur{codprod}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtmdesc">
  <?php if($labels['fafactur{tmdesc}']!='.:') { ?>
  <?php echo label_for('fafactur[tmdesc]', __($labels['fafactur{tmdesc}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{tmdesc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{tmdesc}')): ?>
    <?php echo form_error('fafactur{tmdesc}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, array('getTmdesc',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fafactur[tmdesc]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{tmdesc}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecatra">
  <?php if($labels['fafactur{fecatra}']!='.:') { ?>
  <?php echo label_for('fafactur[fecatra]', __($labels['fafactur{fecatra}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fecatra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fecatra}')): ?>
    <?php echo form_error('fafactur{fecatra}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFecatra', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fecatra]',
  'date_format' => 'dd/MM/yyyy',
  'size' => 10,
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fecatra}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecinidesc">
  <?php if($labels['fafactur{fecinidesc}']!='.:') { ?>
  <?php echo label_for('fafactur[fecinidesc]', __($labels['fafactur{fecinidesc}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fecinidesc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fecinidesc}')): ?>
    <?php echo form_error('fafactur{fecinidesc}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFecinidesc', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fecinidesc]',
  'date_format' => 'dd/MM/yyyy',
  'size' => 10,
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fecinidesc}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecfindesc">
  <?php if($labels['fafactur{fecfindesc}']!='.:') { ?>
  <?php echo label_for('fafactur[fecfindesc]', __($labels['fafactur{fecfindesc}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{fecfindesc}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{fecfindesc}')): ?>
    <?php echo form_error('fafactur{fecfindesc}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($fafactur, 'getFecfindesc', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'fafactur[fecfindesc]',
  'date_format' => 'dd/MM/yyyy',
  'size' => 10,
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{fecfindesc}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divvalcifs">
  <?php if($labels['fafactur{valcifs}']!='.:') { ?>
  <?php echo label_for('fafactur[valcifs]', __($labels['fafactur{valcifs}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fafactur{valcifs}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fafactur{valcifs}')): ?>
    <?php echo form_error('fafactur{valcifs}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fafactur, array('getValcifs',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'fafactur[valcifs]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fafactur{valcifs}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<?php include_partial('edit_actions', array('fafactur' => $fafactur)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fafactur->getId()): ?>
<?php echo button_to(__('delete'), 'fafactur/delete?id='.$fafactur->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>

