<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:45:06
?>
<?php

/**
 * autoNomdefespnivorg actions.
 *
 * @package    Roraima
 * @subpackage autoNomdefespnivorg 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: actions.class.php 32371 2009-09-01 16:06:59Z lhernandez $
 */
class autoNomdefespnivorgActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('nomdefespnivorg', 'list');
  }

  public function executeList()
  {
    $this->processSort();

    $this->processFilters();

    $this->filters = $this->getUser()->getAttributeHolder()->getAll('sf_admin/npestorg/filters');


     // 15    // pager
    $this->pager = new sfPropelPager('Npestorg', 15);
    $c = new Criteria();
    $this->addSortCriteria($c);
    $this->addFiltersCriteria($c);
    $this->pager->setCriteria($c);
    $this->pager->setPage($this->getRequestParameter('page', 1));
    $this->pager->init();
  }

  public function executeCreate()
  {
    return $this->forward('nomdefespnivorg', 'edit');
  }

  public function executeSave()
  {
    return $this->forward('nomdefespnivorg', 'edit');
  }

  /**
   * Función principal para el manejo de las acciones create y edit
   * del formulario.
   *
   */
  public function executeEdit()
  {
    $this->npestorg = $this->getNpestorgOrCreate();

    if ($this->getRequest()->getMethod() == sfRequest::POST)
    {
      $this->updateNpestorgFromRequest();

      $this->saveNpestorg($this->npestorg);

      $this->setFlash('notice', 'Your modifications have been saved');

    $this->Bitacora('Guardo');

      if ($this->getRequestParameter('save_and_add'))
      {
        return $this->redirect('nomdefespnivorg/create');
      }
      else if ($this->getRequestParameter('save_and_list'))
      {
        return $this->redirect('nomdefespnivorg/list');
      }
      else
      {
        return $this->redirect('nomdefespnivorg/edit?id='.$this->npestorg->getId());
      }
    }
    else
    {
      $this->labels = $this->getLabels();
    }
  }

  public function executeDelete()
  {
    $this->npestorg = NpestorgPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->npestorg);

    try
    {
      $this->deleteNpestorg($this->npestorg);
      $this->Bitacora('Elimino');
    }
    catch (PropelException $e)
    {
      $this->getRequest()->setError('delete', 'No se pudo borrar la registro seleccionado. Asegúrese de que no tiene ningún tipo de registros asociados.');
      return $this->forward('nomdefespnivorg', 'list');
    }

    return $this->redirect('nomdefespnivorg/list');
  }

  public function handleErrorEdit()
  {
    $this->preExecute();
    $this->npestorg = $this->getNpestorgOrCreate();
    $this->updateNpestorgFromRequest();

    $this->labels = $this->getLabels();

    return sfView::SUCCESS;
  }

  protected function saveNpestorg($npestorg)
  {
    $npestorg->save();

  }

  protected function deleteNpestorg($npestorg)
  {
    $npestorg->delete();
  }

  protected function updateNpestorgFromRequest()
  {
    $npestorg = $this->getRequestParameter('npestorg');

    if (isset($npestorg['codniv']))
    {
      $this->npestorg->setCodniv($npestorg['codniv']);
    }
    if (isset($npestorg['desniv']))
    {
      $this->npestorg->setDesniv($npestorg['desniv']);
    }
    if (isset($npestorg['telext']))
    {
      $this->npestorg->setTelext($npestorg['telext']);
    }
    if (isset($npestorg['email']))
    {
      $this->npestorg->setEmail($npestorg['email']);
    }
    if (isset($npestorg['codsitent']))
    {
      $this->npestorg->setCodsitent($npestorg['codsitent']);
    }
    if (isset($npestorg['coddep']))
    {
      $this->npestorg->setCoddep($npestorg['coddep']);
    }
    if (isset($npestorg['staact']))
    {
      $this->npestorg->setStaact($npestorg['staact']);
    }
  }

  protected function getNpestorgOrCreate($id = 'id')
  {
    if (!$this->getRequestParameter($id))
    {
      $npestorg = new Npestorg();
    }
    else
    {
      $npestorg = NpestorgPeer::retrieveByPk($this->getRequestParameter($id));

      $this->forward404Unless($npestorg);
    }

    return $npestorg;
  }

  protected function processFilters()
  {
    if ($this->getRequest()->hasParameter('filter'))
    {
      $filters = $this->getRequestParameter('filters');

      $this->getUser()->getAttributeHolder()->removeNamespace('sf_admin/npestorg/filters');
      $this->getUser()->getAttributeHolder()->add($filters, 'sf_admin/npestorg/filters');
    }
  }

  protected function processSort()
  {
    if ($this->getRequestParameter('sort'))
    {
      $this->getUser()->setAttribute('sort', $this->getRequestParameter('sort'), 'sf_admin/npestorg/sort');
      $this->getUser()->setAttribute('type', $this->getRequestParameter('type', 'asc'), 'sf_admin/npestorg/sort');
    }

    if (!$this->getUser()->getAttribute('sort', null, 'sf_admin/npestorg/sort'))
    {
      $this->getUser()->setAttribute('sort', 'codniv', 'sf_admin/npestorg/sort');
      $this->getUser()->setAttribute('type', 'asc', 'sf_admin/npestorg/sort');
    }
  }

   protected function addFiltersCriteria($c)
  {
    if (isset($this->filters['codniv_is_empty']))
    {
      $criterion = $c->getNewCriterion(NpestorgPeer::CODNIV, '');
      $criterion->addOr($c->getNewCriterion(NpestorgPeer::CODNIV, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['codniv']) && $this->filters['codniv'] !== '')
    {
      $c->add(NpestorgPeer::CODNIV, '%'.strtr($this->filters['codniv'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
    if (isset($this->filters['desniv_is_empty']))
    {
      $criterion = $c->getNewCriterion(NpestorgPeer::DESNIV, '');
      $criterion->addOr($c->getNewCriterion(NpestorgPeer::DESNIV, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['desniv']) && $this->filters['desniv'] !== '')
    {
      $c->add(NpestorgPeer::DESNIV, '%'.strtr($this->filters['desniv'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
    if (isset($this->filters['codsitent_is_empty']))
    {
      $criterion = $c->getNewCriterion(NpestorgPeer::CODSITENT, '');
      $criterion->addOr($c->getNewCriterion(NpestorgPeer::CODSITENT, null, Criteria::ISNULL));
      $c->add($criterion);
    }
    else if (isset($this->filters['codsitent']) && $this->filters['codsitent'] !== '')
    {
      $c->add(NpestorgPeer::CODSITENT, '%'.strtr($this->filters['codsitent'], '*', '%').'%', Criteria::LIKE);
    $c->setIgnoreCase(true);
    }
  }
  protected function addSortCriteria($c)
  {
    if ($sort_column = $this->getUser()->getAttribute('sort', null, 'sf_admin/npestorg/sort'))
    {
      $sort_column = NpestorgPeer::translateFieldName($sort_column, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_COLNAME);
      if ($this->getUser()->getAttribute('type', null, 'sf_admin/npestorg/sort') == 'asc')
      {
        $c->addAscendingOrderByColumn($sort_column);
      }
      else
      {
        $c->addDescendingOrderByColumn($sort_column);
      }
    }
  }

  protected function getLabels()
  {
    return array(
      'npestorg{codniv}' => 'Código:',
      'npestorg{desniv}' => 'Descripción:',
      'npestorg{telext}' => 'Teléfono / Extensión:',
      'npestorg{email}' => 'Email:',
      'npestorg{codsitent}' => 'Entrega Bono Alimentación:',
      'npestorg{coddep}' => 'Dependencia:',
      'npestorg{staact}' => 'Estatus:',
    );
  }

    public function executeCatalogo()
  {
    $codigo = $this->getRequestParameter('codigo','');
    $clase = $this->getRequestParameter('clase','');
    $nombre = $this->getRequestParameter('name','');
    $campobase = $this->getRequestParameter('campobase','');
    $campoprincipal = $this->getRequestParameter('campoprincipal','');
    $camposecundario = $this->getRequestParameter('camposecundario','');

    $c = new Criteria();
    eval('$c->add('.ucfirst(strtolower($clase)).'Peer::'.strtoupper($campoprincipal).','.chr(39).$codigo.chr(39).');');
    eval('$peer = '.ucfirst(strtolower($clase)).'Peer::doSelectOne($c);');

  eval('$cajasec = "'.strtolower($nombre).'_'.strtolower($camposecundario).'";');
  eval('$cajaid = "'.strtolower($nombre).'_'.strtolower($campobase).'";');
  $valsec="";
  $valid="";
  eval('if ($peer) $valsec = $peer->get'.H::ObtenerNombreCampo($camposecundario).'();');
  eval('if ($peer) $valid = $peer->getId();');
  $output = '[["'.$cajasec.'","'.$valsec.'",""],["'.$cajaid.'","'.$valid.'",""],["","",""]]';
    $this->getResponse()->setHttpHeader("X-JSON", '('.$output.')');
    return sfView::HEADER_ONLY;
  }

  public function SalvarBitacora($id, $acc)
  {
    try{
      $segbitaco= new Segbitaco();
      $fecha=date('Y-m-d');

      $segbitaco->setCodintusu($this->getUser()->getAttribute('usuario_id'));
      $segbitaco->setTipope(substr($acc, 0, 1));
      $segbitaco->setCodmod('nomdefespnivorg');
      $segbitaco->setValcla('Npestorg');
      $segbitaco->setCodapl(substr(SF_APP, 0, 3));
      $segbitaco->setFecope($fecha);
      $segbitaco->setHorope(time('h:i:s'));
      $segbitaco->setRefmov($id);
      $segbitaco->save();
    }catch(Exception $e){

    }
  }

  public function Bitacora($acc)
  {
    if ($this->npestorg )
    {
      $id= $this->npestorg->getId();
      $this->SalvarBitacora($id ,$acc);
    }
  }

}
