<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:09:07
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomdefespcar 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_actions.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'nomdefespcar/list?id='.$npcargos->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag_click(__('save'), array (
  'name' => 'save',
  'form' => 'sf_admin_edit_form',
  'class' => 'sf_admin_action_save',
)) ?></li>
      <li><?php echo button_to(__('create'), 'nomdefespcar/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
