<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:36:25
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmregrec 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _filters.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('almregrec/list', array('method' => 'get','name'=>'sf_admin_filters_form')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_codrec"><?php echo __('Código:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[codrec]', isset($filters['codrec']) ? $filters['codrec'] : null, array (
  'size' => 10,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_codtiprec"><?php echo __('Grupo:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['codtiprec']) ? $filters['codtiprec'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'Catiprec',
  'text_method' => '__toString',
  'control_name' => 'filters[codtiprec]',
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'almregrec/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_codrec)
	    {
	    	obj = document.sf_admin_filters_form.filters_codrec;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_desrec)
	    {
	    	obj = document.sf_admin_filters_form.filters_desrec;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_limrec)
	    {
	    	obj = document.sf_admin_filters_form.filters_limrec;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_fecemi)
	    {
	    	obj = document.sf_admin_filters_form.filters_fecemi;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_fecven)
	    {
	    	obj = document.sf_admin_filters_form.filters_fecven;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_canutr)
	    {
	    	obj = document.sf_admin_filters_form.filters_canutr;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_codtiprec)
	    {
	    	obj = document.sf_admin_filters_form.filters_codtiprec;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_observ)
	    {
	    	obj = document.sf_admin_filters_form.filters_observ;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_puntua)
	    {
	    	obj = document.sf_admin_filters_form.filters_puntua;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
