<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:33:12
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmdefubi 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_codubi">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/cadefubi/sort') == 'codubi'): ?>
      <?php echo link_to(__('Código'), 'almdefubi/list?sort=codubi&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefubi/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefubi/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Código'), 'almdefubi/list?sort=codubi&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomubi">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/cadefubi/sort') == 'nomubi'): ?>
      <?php echo link_to(__('Descripción'), 'almdefubi/list?sort=nomubi&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefubi/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/cadefubi/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Descripción'), 'almdefubi/list?sort=nomubi&type=asc') ?>
      <?php endif; ?>
          </th>
