<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:33:12
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoAlmdefubi 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: editSuccess.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Definición de Ubicaciones', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('almdefubi/edit_header', array('cadefubi' => $cadefubi)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('almdefubi/edit_messages', array('cadefubi' => $cadefubi, 'labels' => $labels)) ?>
<?php include_partial('almdefubi/edit_form', array('cadefubi' => $cadefubi, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('almdefubi/edit_footer', array('cadefubi' => $cadefubi)) ?>
</div>

</div>
