<?php
// auto-generated by PropelCidesa
// date: 2013/05/27 12:38:39
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php echo form_tag('viasolviatra/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($viasolviatra, 'getId') ?>

<?php
  $fields = ViasolviatraPeer::getFieldNames();

  if(array_search('Codalmusu', $fields))
  {  ?>
  <h2 class="h2" onclick="javascript: return $('divusualms').toggle();"><?php echo __('Almacenes') ?></h2>
  <fieldset id="sf_fieldset_usualms" class="">
  <div class="form-row" id="divusualms">
    <?php echo label_for('viasolviatra[codalmusu]', __('Almacenes Por Usuario: '), 'class="required" Style="text-align:left; width:150px"') ?>
    <div class="content">
    <?php
      $almacenes = $sf_user->getAttribute('usualms',array());
      if(count($almacenes)>0){
        $keys = array_keys($almacenes);
        $codalm = $keys[0];
      }else $codalm = '';
      if($codalm == '') echo label_for('viasolviatra[codalmusu]', __('Usuario sin Almacen Asociado'), 'class="required" Style="text-align:left; width:150px"').'<br><br><br>';
      else echo select_tag('viasolviatra[codalmusu]',options_for_select($almacenes,$viasolviatra->getCodalmusu()!='' ? $viasolviatra->getCodalmusu() : $codalm), ( ($viasolviatra->getId()) ? 'disabled=true' : '').' style=width:500px');
    ?>
    </div>
  </div>
  </fieldset>
<?php } ?>
<?php $cambiareti=H::getConfApp2('cameti', 'viaticos', 'viasolviatra');?>
<?php echo object_input_hidden_tag($viasolviatra, 'getNomempe', array('id' => 'viasolviatra_nomempe', 'name' => 'viasolviatra[nomempe]')) ?>
<?php echo object_input_hidden_tag($viasolviatra, 'getStatus', array('id' => 'viasolviatra_status', 'name' => 'viasolviatra[status]')) ?>
<?php echo object_input_hidden_tag($viasolviatra, 'getCodnivorg', array('id' => 'viasolviatra_codnivorg', 'name' => 'viasolviatra[codnivorg]')) ?>

<h2 class="h2" onclick="javascript: return $('divDatos Generales de la Solicitud').toggle();"><?php if ($cambiareti=='S') echo __('Datos Generales de la Orden'); else echo __('Datos Generales de la Solicitud'); ?></h2>
<fieldset id="sf_fieldset_datos_generales_de_la_solicitud" class="">

<div class="form-row" id="divDatos Generales de la Solicitud">
<div id="diveti">
  <?php if($labels['viasolviatra{eti}']!='.:') { ?>
  <?php echo label_for('viasolviatra[eti]', __($labels['viasolviatra{eti}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{eti}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{eti}')): ?>
    <?php echo form_error('viasolviatra{eti}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('eti', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{eti}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumsol">
  <?php if($labels['viasolviatra{numsol}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numsol]', __($labels['viasolviatra{numsol}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numsol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numsol}')): ?>
    <?php echo form_error('viasolviatra{numsol}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumsol', array (
  'size' => 10,
  'control_name' => 'viasolviatra[numsol]',
  'maxlength' => 10,
  'onBlur' => 'rellenar(this.id)',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numsol}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecsol">
  <?php if($labels['viasolviatra{fecsol}']!='.:') { ?>
  <?php echo label_for('viasolviatra[fecsol]', __($labels['viasolviatra{fecsol}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{fecsol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{fecsol}')): ?>
    <?php echo form_error('viasolviatra{fecsol}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($viasolviatra, 'getFecsol', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'viasolviatra[fecsol]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{fecsol}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divptipvia">
  <?php if($labels['viasolviatra{ptipvia}']!='.:') { ?>
  <?php echo label_for('viasolviatra[ptipvia]', __($labels['viasolviatra{ptipvia}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{ptipvia}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{ptipvia}')): ?>
    <?php echo form_error('viasolviatra{ptipvia}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('ptipvia', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{ptipvia}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divdessol">
  <?php if($labels['viasolviatra{dessol}']!='.:') { ?>
  <?php echo label_for('viasolviatra[dessol]', __($labels['viasolviatra{dessol}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{dessol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{dessol}')): ?>
    <?php echo form_error('viasolviatra{dessol}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($viasolviatra, 'getDessol', array (
  'control_name' => 'viasolviatra[dessol]',
  'cols' => 65,
  'maxlength' => 1000,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{dessol}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodeve">
  <?php if($labels['viasolviatra{codeve}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codeve]', __($labels['viasolviatra{codeve}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codeve}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codeve}')): ?>
    <?php echo form_error('viasolviatra{codeve}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 14, array (
  'getprincipal' => 'getCodeve',
  'getsecundario' => 'getDeseve',
  'campoprincipal' => 'codeve',
  'camposecundario' => 'deseve',
  'campobase' => 'id',
),  'Preprecom_Cpevepre',  'Cpevepre',  '',  '',  '');?>

    
  <?php if($labels['viasolviatra{codeve}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcoddirec">
  <?php if($labels['viasolviatra{coddirec}']!='.:') { ?>
  <?php echo label_for('viasolviatra[coddirec]', __($labels['viasolviatra{coddirec}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{coddirec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{coddirec}')): ?>
    <?php echo form_error('viasolviatra{coddirec}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 11, array (
  'getprincipal' => 'getCoddirec',
  'getsecundario' => 'getDesdirec',
  'campoprincipal' => 'coddirec',
  'camposecundario' => 'desdirec',
  'campobase' => 'id',
),  'Cadefdirec_Almdefdiv',  'cadefdirec',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{coddirec}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divDatos Empleado Solicitante').toggle();"><?php echo __('Datos Empleado Solicitante') ?></h2>
<fieldset id="sf_fieldset_datos_empleado_solicitante" class="">

<div class="form-row" id="divDatos Empleado Solicitante">
<div id="divesnoemp">
  <?php if($labels['viasolviatra{esnoemp}']!='.:') { ?>
  <?php echo label_for('viasolviatra[esnoemp]', __($labels['viasolviatra{esnoemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{esnoemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{esnoemp}')): ?>
    <?php echo form_error('viasolviatra{esnoemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($viasolviatra, 'getEsnoemp', array (
  'control_name' => 'viasolviatra[esnoemp]',
  'onClick' => 'MostraCat()',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{esnoemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodemp">
  <?php if($labels['viasolviatra{codemp}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codemp]', __($labels['viasolviatra{codemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codemp}')): ?>
    <?php echo form_error('viasolviatra{codemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codemp', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{codemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcedemp">
  <?php if($labels['viasolviatra{cedemp}']!='.:') { ?>
  <?php echo label_for('viasolviatra[cedemp]', __($labels['viasolviatra{cedemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{cedemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{cedemp}')): ?>
    <?php echo form_error('viasolviatra{cedemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getCedemp', array (
  'disabled' => true,
  'control_name' => 'viasolviatra[cedemp]',
  'style' => 'border:none',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{cedemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcargo">
  <?php if($labels['viasolviatra{cargo}']!='.:') { ?>
  <?php echo label_for('viasolviatra[cargo]', __($labels['viasolviatra{cargo}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{cargo}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{cargo}')): ?>
    <?php echo form_error('viasolviatra{cargo}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getCargo', array (
  'disabled' => true,
  'control_name' => 'viasolviatra[cargo]',
  'style' => 'border:none',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{cargo}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnivel">
  <?php if($labels['viasolviatra{nivel}']!='.:') { ?>
  <?php echo label_for('viasolviatra[nivel]', __($labels['viasolviatra{nivel}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{nivel}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{nivel}')): ?>
    <?php echo form_error('viasolviatra{nivel}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNivel', array (
  'disabled' => true,
  'control_name' => 'viasolviatra[nivel]',
  'style' => 'border:none',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{nivel}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcat">
  <?php if($labels['viasolviatra{codcat}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codcat]', __($labels['viasolviatra{codcat}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codcat}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codcat}')): ?>
    <?php echo form_error('viasolviatra{codcat}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 15, array (
  'getprincipal' => 'getCodcat',
  'getsecundario' => 'getNomcat',
  'campoprincipal' => 'codcat',
  'camposecundario' => 'nomcat',
  'campobase' => 'id',
),  'NconceptosCat_Asignar',  'Npcatpre',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codcat}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodniv">
  <?php if($labels['viasolviatra{codniv}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codniv]', __($labels['viasolviatra{codniv}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codniv}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codniv}')): ?>
    <?php echo form_error('viasolviatra{codniv}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 0, array (
  'getprincipal' => 'getCodniv',
  'getsecundario' => 'getDesniv',
  'campoprincipal' => 'codniv',
  'camposecundario' => 'desniv',
  'campobase' => 'id',
),  'viadefniv_codniv',  'Viadefniv',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codniv}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgrid">
  <?php if($labels['viasolviatra{grid}']!='.:') { ?>
  <?php echo label_for('viasolviatra[grid]', __($labels['viasolviatra{grid}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{grid}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{grid}')): ?>
    <?php echo form_error('viasolviatra{grid}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('grid', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{grid}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divDetalle de la Solicitud').toggle();"><?php if ($cambiareti=='S') echo __('Detalle de la Orden'); else echo __('Detalle de la Solicitud'); ?></h2>
<fieldset id="sf_fieldset_detalle_de_la_solicitud" class="">

<div class="form-row" id="divDetalle de la Solicitud">
<div id="divcodpai">
  <?php if($labels['viasolviatra{codpai}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codpai]', __($labels['viasolviatra{codpai}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codpai}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codpai}')): ?>
    <?php echo form_error('viasolviatra{codpai}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 7, array (
  'getprincipal' => 'getCodpai',
  'getsecundario' => 'getNompai',
  'campoprincipal' => 'codpai',
  'camposecundario' => 'nompai',
  'campobase' => 'id',
),  'viaestado_codpai',  'Viapais',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codpai}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodest">
  <?php if($labels['viasolviatra{codest}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codest]', __($labels['viasolviatra{codest}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codest}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codest}')): ?>
    <?php echo form_error('viasolviatra{codest}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 6, array (
  'getprincipal' => 'getCodest',
  'getsecundario' => 'getNomest',
  'campoprincipal' => 'codest',
  'camposecundario' => 'nomest',
  'campobase' => 'id',
),  'viaestado_codest',  'Viaestado',  '/param1/'."'+$('viasolviatra_codpai').value+'".'',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codest}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodmun">
  <?php if($labels['viasolviatra{codmun}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codmun]', __($labels['viasolviatra{codmun}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codmun}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codmun}')): ?>
    <?php echo form_error('viasolviatra{codmun}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 13, array (
  'getprincipal' => 'getCodmun',
  'getsecundario' => 'getNommun',
  'campoprincipal' => 'codmun',
  'camposecundario' => 'nommun',
  'campobase' => 'id',
),  'viamunicip_codmun',  'Viamunicip',  '/param1/'."'+$('viasolviatra_codest').value+'".'',  '+'."'".'&estado='."'+$('viasolviatra_codest').value".'',  '');?>

    
  <?php if($labels['viasolviatra{codmun}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodciu">
  <?php if($labels['viasolviatra{codciu}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codciu]', __($labels['viasolviatra{codciu}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codciu}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codciu}')): ?>
    <?php echo form_error('viasolviatra{codciu}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 0, array (
  'getprincipal' => 'getCodciu',
  'getsecundario' => 'getNomciu',
  'campoprincipal' => 'codciu',
  'camposecundario' => 'nomciu',
  'campobase' => 'id',
),  'viaciudad_codciu',  'Viaciudad',  '/param1/'."'+$('viasolviatra_codest').value+'".'/param2/'."'+$('viasolviatra_codpai').value+'".'',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codciu}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodproced">
  <?php if($labels['viasolviatra{codproced}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codproced]', __($labels['viasolviatra{codproced}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codproced}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codproced}')): ?>
    <?php echo form_error('viasolviatra{codproced}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 0, array (
  'getprincipal' => 'getCodproced',
  'getsecundario' => 'getDesproced',
  'campoprincipal' => 'codproced',
  'camposecundario' => 'desproced',
  'campobase' => 'id',
),  'viadefproced_codproced',  'Viadefproced',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codproced}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodpro">
  <?php if($labels['viasolviatra{codpro}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codpro]', __($labels['viasolviatra{codpro}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codpro}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codpro}')): ?>
    <?php echo form_error('viasolviatra{codpro}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('codpro', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{codpro}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecdes">
  <?php if($labels['viasolviatra{fecdes}']!='.:') { ?>
  <?php echo label_for('viasolviatra[fecdes]', __($labels['viasolviatra{fecdes}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{fecdes}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{fecdes}')): ?>
    <?php echo form_error('viasolviatra{fecdes}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($viasolviatra, 'getFecdes', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'viasolviatra[fecdes]',
  'onchange' => 'CalculaDias(this.id)',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{fecdes}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfechas">
  <?php if($labels['viasolviatra{fechas}']!='.:') { ?>
  <?php echo label_for('viasolviatra[fechas]', __($labels['viasolviatra{fechas}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{fechas}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{fechas}')): ?>
    <?php echo form_error('viasolviatra{fechas}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($viasolviatra, 'getFechas', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'viasolviatra[fechas]',
  'onchange' => 'CalculaDias(this.id)',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{fechas}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumdia">
  <?php if($labels['viasolviatra{numdia}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numdia]', __($labels['viasolviatra{numdia}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numdia}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numdia}')): ?>
    <?php echo form_error('viasolviatra{numdia}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumdia', array (
  'size' => 7,
  'onKeyPress' => 'javascript:return validaEntero(event)',
  'control_name' => 'viasolviatra[numdia]',
  'readOnly' => true,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numdia}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodfortra">
  <?php if($labels['viasolviatra{codfortra}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codfortra]', __($labels['viasolviatra{codfortra}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codfortra}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codfortra}')): ?>
    <?php echo form_error('viasolviatra{codfortra}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 0, array (
  'getprincipal' => 'getCodfortra',
  'getsecundario' => 'getDesfortra',
  'campoprincipal' => 'codfortra',
  'camposecundario' => 'desfortra',
  'campobase' => 'id',
),  'viadeffortra_codfortra',  'Viadeffortra',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codfortra}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodubi">
  <?php if($labels['viasolviatra{codubi}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codubi]', __($labels['viasolviatra{codubi}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codubi}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codubi}')): ?>
    <?php echo form_error('viasolviatra{codubi}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 8, array (
  'getprincipal' => 'getCodubi',
  'getsecundario' => 'getDesubi',
  'campoprincipal' => 'codubi',
  'camposecundario' => 'desubi',
  'campobase' => 'id',
),  'Bnubica_Almordcom',  'Bnubica',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codubi}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodcen">
  <?php if($labels['viasolviatra{codcen}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codcen]', __($labels['viasolviatra{codcen}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codcen}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codcen}')): ?>
    <?php echo form_error('viasolviatra{codcen}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 9, array (
  'getprincipal' => 'getCodcen',
  'getsecundario' => 'getDescen',
  'campoprincipal' => 'codcen',
  'camposecundario' => 'descen',
  'campobase' => 'id',
),  'Cadefcen_Almsolegr',  'Cadefcen',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codcen}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodempaut">
  <?php if($labels['viasolviatra{codempaut}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codempaut]', __($labels['viasolviatra{codempaut}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codempaut}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codempaut}')): ?>
    <?php echo form_error('viasolviatra{codempaut}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 5, array (
  'getprincipal' => 'getCodempaut',
  'getsecundario' => 'getNomempaut',
  'campoprincipal' => 'codempaut',
  'camposecundario' => 'nomempaut',
  'campobase' => 'id',
),  'Nphojint',  'Nphojint',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codempaut}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcedempaut">
  <?php if($labels['viasolviatra{cedempaut}']!='.:') { ?>
  <?php echo label_for('viasolviatra[cedempaut]', __($labels['viasolviatra{cedempaut}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{cedempaut}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{cedempaut}')): ?>
    <?php echo form_error('viasolviatra{cedempaut}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getCedempaut', array (
  'disabled' => true,
  'control_name' => 'viasolviatra[cedempaut]',
  'style' => 'border:none',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{cedempaut}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnivelaut">
  <?php if($labels['viasolviatra{nivelaut}']!='.:') { ?>
  <?php echo label_for('viasolviatra[nivelaut]', __($labels['viasolviatra{nivelaut}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{nivelaut}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{nivelaut}')): ?>
    <?php echo form_error('viasolviatra{nivelaut}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNivelaut', array (
  'disabled' => true,
  'control_name' => 'viasolviatra[nivelaut]',
  'style' => 'border:none',
  'size' => 80,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{nivelaut}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtipbol">
  <?php if($labels['viasolviatra{tipbol}']!='.:') { ?>
  <?php echo label_for('viasolviatra[tipbol]', __($labels['viasolviatra{tipbol}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{tipbol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{tipbol}')): ?>
    <?php echo form_error('viasolviatra{tipbol}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('tipbol', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{tipbol}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmonbol">
  <?php if($labels['viasolviatra{monbol}']!='.:') { ?>
  <?php echo label_for('viasolviatra[monbol]', __($labels['viasolviatra{monbol}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{monbol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{monbol}')): ?>
    <?php echo form_error('viasolviatra{monbol}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, array('getMonbol',true), array (
  'size' => 7,
  'onKeyPress' => 'return validaDecimal(event)',
  'onBlur' => 'event.keyCode=13;return formatoDecimal(event,this.id)',
  'control_name' => 'viasolviatra[monbol]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{monbol}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divhorsal">
  <?php if($labels['viasolviatra{horsal}']!='.:') { ?>
  <?php echo label_for('viasolviatra[horsal]', __($labels['viasolviatra{horsal}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{horsal}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{horsal}')): ?>
    <?php echo form_error('viasolviatra{horsal}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($viasolviatra, 'getHorsal', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'viasolviatra[horsal]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{horsal}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divhorlle">
  <?php if($labels['viasolviatra{horlle}']!='.:') { ?>
  <?php echo label_for('viasolviatra[horlle]', __($labels['viasolviatra{horlle}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{horlle}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{horlle}')): ?>
    <?php echo form_error('viasolviatra{horlle}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($viasolviatra, 'getHorlle', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'viasolviatra[horlle]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{horlle}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divitinerario">
  <?php if($labels['viasolviatra{itinerario}']!='.:') { ?>
  <?php echo label_for('viasolviatra[itinerario]', __($labels['viasolviatra{itinerario}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{itinerario}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{itinerario}')): ?>
    <?php echo form_error('viasolviatra{itinerario}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($viasolviatra, 'getItinerario', array (
  'control_name' => 'viasolviatra[itinerario]',
  'size' => '80x3',
  'maxlength' => 500,
  'onkeyup' => 'ismaxlength(this)',
)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{itinerario}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divlugsal">
  <?php if($labels['viasolviatra{lugsal}']!='.:') { ?>
  <?php echo label_for('viasolviatra[lugsal]', __($labels['viasolviatra{lugsal}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{lugsal}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{lugsal}')): ?>
    <?php echo form_error('viasolviatra{lugsal}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($viasolviatra, 'getLugsal', array (
  'control_name' => 'viasolviatra[lugsal]',
  'size' => '80x3',
  'maxlength' => 100,
  'onkeyup' => 'ismaxlength(this)',
)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{lugsal}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divOtros Datos').toggle();"><?php echo __('Otros Datos') ?></h2>
<fieldset id="sf_fieldset_otros_datos" class="">

<div class="form-row" id="divOtros Datos">
<div id="divnumpas">
  <?php if($labels['viasolviatra{numpas}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numpas]', __($labels['viasolviatra{numpas}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numpas}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numpas}')): ?>
    <?php echo form_error('viasolviatra{numpas}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumpas', array (
  'size' => 20,
  'control_name' => 'viasolviatra[numpas]',
  'maxlength' => 15,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numpas}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumvis">
  <?php if($labels['viasolviatra{numvis}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numvis]', __($labels['viasolviatra{numvis}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numvis}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numvis}')): ?>
    <?php echo form_error('viasolviatra{numvis}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumvis', array (
  'size' => 20,
  'control_name' => 'viasolviatra[numvis]',
  'maxlength' => 15,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numvis}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumcel">
  <?php if($labels['viasolviatra{numcel}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numcel]', __($labels['viasolviatra{numcel}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numcel}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numcel}')): ?>
    <?php echo form_error('viasolviatra{numcel}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumcel', array (
  'size' => 20,
  'control_name' => 'viasolviatra[numcel]',
  'maxlength' => 15,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numcel}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumext">
  <?php if($labels['viasolviatra{numext}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numext]', __($labels['viasolviatra{numext}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numext}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numext}')): ?>
    <?php echo form_error('viasolviatra{numext}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumext', array (
  'size' => 20,
  'control_name' => 'viasolviatra[numext]',
  'maxlength' => 15,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numext}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divreqhospe">
  <?php if($labels['viasolviatra{reqhospe}']!='.:') { ?>
  <?php echo label_for('viasolviatra[reqhospe]', __($labels['viasolviatra{reqhospe}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{reqhospe}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{reqhospe}')): ?>
    <?php echo form_error('viasolviatra{reqhospe}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('reqhospe', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{reqhospe}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divhosped">
  <?php if($labels['viasolviatra{hosped}']!='.:') { ?>
  <?php echo label_for('viasolviatra[hosped]', __($labels['viasolviatra{hosped}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{hosped}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{hosped}')): ?>
    <?php echo form_error('viasolviatra{hosped}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('hosped', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{hosped}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divobshos">
  <?php if($labels['viasolviatra{obshos}']!='.:') { ?>
  <?php echo label_for('viasolviatra[obshos]', __($labels['viasolviatra{obshos}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{obshos}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{obshos}')): ?>
    <?php echo form_error('viasolviatra{obshos}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($viasolviatra, 'getObshos', array (
  'control_name' => 'viasolviatra[obshos]',
  'size' => '80x3',
  'maxlength' => 1000,
  'onkeyup' => 'ismaxlength(this)',
)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{obshos}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divSolicitud de Boleto Áereo').toggle();"><?php echo __('Solicitud de Boleto Áereo') ?></h2>
<fieldset id="sf_fieldset_solicitud_de_boleto___ereo" class="">

<div class="form-row" id="divSolicitud de Boleto Áereo">
<div id="divreqbolaer">
  <?php if($labels['viasolviatra{reqbolaer}']!='.:') { ?>
  <?php echo label_for('viasolviatra[reqbolaer]', __($labels['viasolviatra{reqbolaer}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{reqbolaer}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{reqbolaer}')): ?>
    <?php echo form_error('viasolviatra{reqbolaer}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('reqbolaer', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{reqbolaer}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgridbolaer">
  <?php if($labels['viasolviatra{gridbolaer}']!='.:') { ?>
  <?php echo label_for('viasolviatra[gridbolaer]', __($labels['viasolviatra{gridbolaer}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{gridbolaer}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{gridbolaer}')): ?>
    <?php echo form_error('viasolviatra{gridbolaer}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('gridbolaer', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{gridbolaer}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtippas">
  <?php if($labels['viasolviatra{tippas}']!='.:') { ?>
  <?php echo label_for('viasolviatra[tippas]', __($labels['viasolviatra{tippas}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{tippas}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{tippas}')): ?>
    <?php echo form_error('viasolviatra{tippas}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('tippas', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{tippas}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecsal">
  <?php if($labels['viasolviatra{fecsal}']!='.:') { ?>
  <?php echo label_for('viasolviatra[fecsal]', __($labels['viasolviatra{fecsal}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{fecsal}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{fecsal}')): ?>
    <?php echo form_error('viasolviatra{fecsal}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($viasolviatra, 'getFecsal', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'viasolviatra[fecsal]',
  'date_format' => 'dd/MM/yyyy',
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{fecsal}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divhorsalb">
  <?php if($labels['viasolviatra{horsalb}']!='.:') { ?>
  <?php echo label_for('viasolviatra[horsalb]', __($labels['viasolviatra{horsalb}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{horsalb}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{horsalb}')): ?>
    <?php echo form_error('viasolviatra{horsalb}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getHorsalb', array (
  'size' => 20,
  'control_name' => 'viasolviatra[horsalb]',
)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{horsalb}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divfecreg">
  <?php if($labels['viasolviatra{fecreg}']!='.:') { ?>
  <?php echo label_for('viasolviatra[fecreg]', __($labels['viasolviatra{fecreg}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{fecreg}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{fecreg}')): ?>
    <?php echo form_error('viasolviatra{fecreg}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_date_tag($viasolviatra, 'getFecreg', array (
  'rich' => true,
  'onkeyup' => 'javascript: mascara(this,\'/\',patron,true)',
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'viasolviatra[fecreg]',
  'date_format' => 'dd/MM/yyyy',
  'maxlength' => 10,
)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{fecreg}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divhorreg">
  <?php if($labels['viasolviatra{horreg}']!='.:') { ?>
  <?php echo label_for('viasolviatra[horreg]', __($labels['viasolviatra{horreg}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{horreg}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{horreg}')): ?>
    <?php echo form_error('viasolviatra{horreg}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getHorreg', array (
  'size' => 20,
  'control_name' => 'viasolviatra[horreg]',
)); echo $value ? $value : '&nbsp;' ?>
      
    
  <?php if($labels['viasolviatra{horreg}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divrutbolaer">
  <?php if($labels['viasolviatra{rutbolaer}']!='.:') { ?>
  <?php echo label_for('viasolviatra[rutbolaer]', __($labels['viasolviatra{rutbolaer}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{rutbolaer}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{rutbolaer}')): ?>
    <?php echo form_error('viasolviatra{rutbolaer}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($viasolviatra, 'getRutbolaer', array (
  'control_name' => 'viasolviatra[rutbolaer]',
  'size' => '80x3',
  'maxlength' => 200,
  'onkeyup' => 'javascript:return ismaxlength(this)',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{rutbolaer}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divmotviabol">
  <?php if($labels['viasolviatra{motviabol}']!='.:') { ?>
  <?php echo label_for('viasolviatra[motviabol]', __($labels['viasolviatra{motviabol}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{motviabol}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{motviabol}')): ?>
    <?php echo form_error('viasolviatra{motviabol}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_textarea_tag($viasolviatra, 'getMotviabol', array (
  'control_name' => 'viasolviatra[motviabol]',
  'size' => '80x3',
  'maxlength' => 500,
  'onkeyup' => 'javascript:return ismaxlength(this)',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{motviabol}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divSolicitud de Transporte Terrestre').toggle();"><?php echo __('Solicitud de Transporte Terrestre') ?></h2>
<fieldset id="sf_fieldset_solicitud_de_transporte_terrestre" class="">

<div class="form-row" id="divSolicitud de Transporte Terrestre">
<div id="divreqtrater">
  <?php if($labels['viasolviatra{reqtrater}']!='.:') { ?>
  <?php echo label_for('viasolviatra[reqtrater]', __($labels['viasolviatra{reqtrater}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{reqtrater}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{reqtrater}')): ?>
    <?php echo form_error('viasolviatra{reqtrater}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('reqtrater', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{reqtrater}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divgridtrater">
  <?php if($labels['viasolviatra{gridtrater}']!='.:') { ?>
  <?php echo label_for('viasolviatra[gridtrater]', __($labels['viasolviatra{gridtrater}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{gridtrater}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{gridtrater}')): ?>
    <?php echo form_error('viasolviatra{gridtrater}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('gridtrater', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{gridtrater}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcodempusu">
  <?php if($labels['viasolviatra{codempusu}']!='.:') { ?>
  <?php echo label_for('viasolviatra[codempusu]', __($labels['viasolviatra{codempusu}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{codempusu}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{codempusu}')): ?>
    <?php echo form_error('viasolviatra{codempusu}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
    
  <?php echo Catalogo($viasolviatra, 12, array (
  'getprincipal' => 'getCodempusu',
  'getsecundario' => 'getNomempusu',
  'campoprincipal' => 'codempusu',
  'camposecundario' => 'nomempusu',
  'campobase' => 'id',
),  'Nphojint',  'Nphojint',  '',  '',  '');?>

  	
  <?php if($labels['viasolviatra{codempusu}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcelemp">
  <?php if($labels['viasolviatra{celemp}']!='.:') { ?>
  <?php echo label_for('viasolviatra[celemp]', __($labels['viasolviatra{celemp}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{celemp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{celemp}')): ?>
    <?php echo form_error('viasolviatra{celemp}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getCelemp', array (
  'size' => 15,
  'maxlength' => 20,
  'control_name' => 'viasolviatra[celemp]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{celemp}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtipserv">
  <?php if($labels['viasolviatra{tipserv}']!='.:') { ?>
  <?php echo label_for('viasolviatra[tipserv]', __($labels['viasolviatra{tipserv}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{tipserv}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{tipserv}')): ?>
    <?php echo form_error('viasolviatra{tipserv}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getTipserv', array (
  'size' => 60,
  'control_name' => 'viasolviatra[tipserv]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{tipserv}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcanvehi">
  <?php if($labels['viasolviatra{canvehi}']!='.:') { ?>
  <?php echo label_for('viasolviatra[canvehi]', __($labels['viasolviatra{canvehi}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{canvehi}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{canvehi}')): ?>
    <?php echo form_error('viasolviatra{canvehi}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getCanvehi', array (
  'size' => 60,
  'control_name' => 'viasolviatra[canvehi]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{canvehi}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divtipvehi">
  <?php if($labels['viasolviatra{tipvehi}']!='.:') { ?>
  <?php echo label_for('viasolviatra[tipvehi]', __($labels['viasolviatra{tipvehi}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{tipvehi}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{tipvehi}')): ?>
    <?php echo form_error('viasolviatra{tipvehi}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getTipvehi', array (
  'size' => 60,
  'control_name' => 'viasolviatra[tipvehi]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{tipvehi}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcandias">
  <?php if($labels['viasolviatra{candias}']!='.:') { ?>
  <?php echo label_for('viasolviatra[candias]', __($labels['viasolviatra{candias}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{candias}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{candias}')): ?>
    <?php echo form_error('viasolviatra{candias}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getCandias', array (
  'size' => 60,
  'control_name' => 'viasolviatra[candias]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{candias}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divcanpasaj">
  <?php if($labels['viasolviatra{canpasaj}']!='.:') { ?>
  <?php echo label_for('viasolviatra[canpasaj]', __($labels['viasolviatra{canpasaj}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{canpasaj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{canpasaj}')): ?>
    <?php echo form_error('viasolviatra{canpasaj}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getCanpasaj', array (
  'size' => 60,
  'control_name' => 'viasolviatra[canpasaj]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{canpasaj}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divequipaj">
  <?php if($labels['viasolviatra{equipaj}']!='.:') { ?>
  <?php echo label_for('viasolviatra[equipaj]', __($labels['viasolviatra{equipaj}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{equipaj}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{equipaj}')): ?>
    <?php echo form_error('viasolviatra{equipaj}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($viasolviatra, 'getEquipaj', array (
  'control_name' => 'viasolviatra[equipaj]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{equipaj}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divinstrum">
  <?php if($labels['viasolviatra{instrum}']!='.:') { ?>
  <?php echo label_for('viasolviatra[instrum]', __($labels['viasolviatra{instrum}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{instrum}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{instrum}')): ?>
    <?php echo form_error('viasolviatra{instrum}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($viasolviatra, 'getInstrum', array (
  'control_name' => 'viasolviatra[instrum]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{instrum}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divbultos">
  <?php if($labels['viasolviatra{bultos}']!='.:') { ?>
  <?php echo label_for('viasolviatra[bultos]', __($labels['viasolviatra{bultos}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{bultos}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{bultos}')): ?>
    <?php echo form_error('viasolviatra{bultos}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($viasolviatra, 'getBultos', array (
  'control_name' => 'viasolviatra[bultos]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{bultos}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divconesper">
  <?php if($labels['viasolviatra{conesper}']!='.:') { ?>
  <?php echo label_for('viasolviatra[conesper]', __($labels['viasolviatra{conesper}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{conesper}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{conesper}')): ?>
    <?php echo form_error('viasolviatra{conesper}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($viasolviatra, 'getConesper', array (
  'control_name' => 'viasolviatra[conesper]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{conesper}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divadisposi">
  <?php if($labels['viasolviatra{adisposi}']!='.:') { ?>
  <?php echo label_for('viasolviatra[adisposi]', __($labels['viasolviatra{adisposi}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{adisposi}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{adisposi}')): ?>
    <?php echo form_error('viasolviatra{adisposi}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_checkbox_tag($viasolviatra, 'getAdisposi', array (
  'control_name' => 'viasolviatra[adisposi]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{adisposi}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<h2 class="h2" onclick="javascript: return $('divDatos de la Persona Contacto en caso de Emergencia').toggle();"><?php echo __('Datos de la Persona Contacto en caso de Emergencia') ?></h2>
<fieldset id="sf_fieldset_datos_de_la_persona_contacto_en_caso_de_emergencia" class="">

<div class="form-row" id="divDatos de la Persona Contacto en caso de Emergencia">
<div id="divapepercon">
  <?php if($labels['viasolviatra{apepercon}']!='.:') { ?>
  <?php echo label_for('viasolviatra[apepercon]', __($labels['viasolviatra{apepercon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{apepercon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{apepercon}')): ?>
    <?php echo form_error('viasolviatra{apepercon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getApepercon', array (
  'size' => 55,
  'control_name' => 'viasolviatra[apepercon]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{apepercon}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnompercon">
  <?php if($labels['viasolviatra{nompercon}']!='.:') { ?>
  <?php echo label_for('viasolviatra[nompercon]', __($labels['viasolviatra{nompercon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{nompercon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{nompercon}')): ?>
    <?php echo form_error('viasolviatra{nompercon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNompercon', array (
  'size' => 55,
  'control_name' => 'viasolviatra[nompercon]',
  'maxlength' => 50,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{nompercon}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divparpercon">
  <?php if($labels['viasolviatra{parpercon}']!='.:') { ?>
  <?php echo label_for('viasolviatra[parpercon]', __($labels['viasolviatra{parpercon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{parpercon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{parpercon}')): ?>
    <?php echo form_error('viasolviatra{parpercon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('parpercon', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{parpercon}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumhabpercon">
  <?php if($labels['viasolviatra{numhabpercon}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numhabpercon]', __($labels['viasolviatra{numhabpercon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numhabpercon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numhabpercon}')): ?>
    <?php echo form_error('viasolviatra{numhabpercon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumhabpercon', array (
  'size' => 20,
  'control_name' => 'viasolviatra[numhabpercon]',
  'maxlength' => 15,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numhabpercon}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divnumcelpercon">
  <?php if($labels['viasolviatra{numcelpercon}']!='.:') { ?>
  <?php echo label_for('viasolviatra[numcelpercon]', __($labels['viasolviatra{numcelpercon}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{numcelpercon}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{numcelpercon}')): ?>
    <?php echo form_error('viasolviatra{numcelpercon}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($viasolviatra, 'getNumcelpercon', array (
  'size' => 20,
  'control_name' => 'viasolviatra[numcelpercon]',
  'maxlength' => 15,
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{numcelpercon}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
<div id="divjs">
  <?php if($labels['viasolviatra{js}']!='.:') { ?>
  <?php echo label_for('viasolviatra[js]', __($labels['viasolviatra{js}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('viasolviatra{js}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('viasolviatra{js}')): ?>
    <?php echo form_error('viasolviatra{js}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = get_partial('js', array('type' => 'edit', 'viasolviatra' => $viasolviatra,'labels' => $labels,'params' => $params)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['viasolviatra{js}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<?php include_partial('edit_actions', array('viasolviatra' => $viasolviatra)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($viasolviatra->getId()): ?>
<?php echo button_to(__('delete'), 'viasolviatra/delete?id='.$viasolviatra->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>

<script type="text/javascript"language="Javascript">

var grabo='<?php echo $grabo;?>';
var mosforpreimp="<?php echo H::getConfApp2('mosforpreimp', 'viaticos', 'viasolviatra');?>";

if (mosforpreimp=='S' && grabo=='S')
{
  Mostrar_orden_preimpresa();
}

</script>