<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:36:53
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoApliuser 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_actions.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'apliuser/edit?id='.$apli_user->getId()) ?></li>
</ul>
</td>
