<?php
// auto-generated by PropelCidesa
// date: 2017/02/17 10:36:24
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _filters.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>
 
<?php use_helper('Object') ?>

<div class="sf_admin_filters">
<?php echo form_tag('fadefprg/list', array('method' => 'get','name'=>'sf_admin_filters_form')) ?>

  <fieldset>
    <h2><?php echo __('filters') ?></h2>
    <div class="form-row">
    <label for="filters_codprg"><?php echo __('Código:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[codprg]', isset($filters['codprg']) ? $filters['codprg'] : null, array (
  'size' => 5,
  'maxlength' => 4,
  'onFocus' => 'readonly(this.id)',
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_desprg"><?php echo __('Descripción:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[desprg]', isset($filters['desprg']) ? $filters['desprg'] : null, array (
  'size' => 80,
  'maxlength' => 30,
)) ?>
    </div>
    </div>

        <div class="form-row">
    <label for="filters_espae"><?php echo __('Es PAE (S->Si o N->No):') ?></label>
    <div class="content">
    <?php echo input_tag('filters[espae]', isset($filters['espae']) ? $filters['espae'] : null, array (
  'size' => 1,
)) ?>
    </div>
    </div>

      </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'fadefprg/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_codprg)
	    {
	    	obj = document.sf_admin_filters_form.filters_codprg;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_desprg)
	    {
	    	obj = document.sf_admin_filters_form.filters_desprg;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_espae)
	    {
	    	obj = document.sf_admin_filters_form.filters_espae;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
	<script language="JavaScript" type="text/javascript">
	    if(document.sf_admin_filters_form.filters_id)
	    {
	    	obj = document.sf_admin_filters_form.filters_id;
			opt = obj.getElementsByTagName('optgroup');
			for (i=0;i<opt.length;i++)
		    opt[i].label='';
	    }
	</script>
