<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:46:19
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomnomcalnom 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<?php echo form_tag('nomnomcalnom/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($npnomina, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

</fieldset>
<fieldset id="sf_fieldset_editable" class="">
<h2><?php echo __('Editable') ?></h2>


<div class="form-row">
  <?php echo label_for('npnomina[codnom]', __($labels['npnomina{codnom}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npnomina{codnom}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npnomina{codnom}')): ?>
    <?php echo form_error('npnomina{codnom}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npnomina, 'getCodnom', array (
  'size' => 20,
  'control_name' => 'npnomina[codnom]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('npnomina[numsem]', __($labels['npnomina{numsem}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('npnomina{numsem}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npnomina{numsem}')): ?>
    <?php echo form_error('npnomina{numsem}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($npnomina, 'getNumsem', array (
  'size' => 7,
  'control_name' => 'npnomina[numsem]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('npnomina[ultfec]', __($labels['npnomina{ultfec}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npnomina{ultfec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npnomina{ultfec}')): ?>
    <?php echo form_error('npnomina{ultfec}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($npnomina, 'getUltfec', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'npnomina[ultfec]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('npnomina[profec]', __($labels['npnomina{profec}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('npnomina{profec}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('npnomina{profec}')): ?>
    <?php echo form_error('npnomina{profec}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($npnomina, 'getProfec', array (
  'rich' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'npnomina[profec]',
  'date_format' => 'dd/MM/yyyy',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('npnomina' => $npnomina)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($npnomina->getId()): ?>
<?php echo button_to(__('delete'), 'nomnomcalnom/delete?id='.$npnomina->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
