<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:46:19
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomnomcalnom 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_codnom">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'codnom'): ?>
      <?php echo link_to(__('Código'), 'nomnomcalnom/list?sort=codnom&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Código'), 'nomnomcalnom/list?sort=codnom&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomnom">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'nomnom'): ?>
      <?php echo link_to(__('Nomnom'), 'nomnomcalnom/list?sort=nomnom&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nomnom'), 'nomnomcalnom/list?sort=nomnom&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_frecal">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'frecal'): ?>
      <?php echo link_to(__('Frecal'), 'nomnomcalnom/list?sort=frecal&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Frecal'), 'nomnomcalnom/list?sort=frecal&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_ultfec">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'ultfec'): ?>
      <?php echo link_to(__('Desde'), 'nomnomcalnom/list?sort=ultfec&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Desde'), 'nomnomcalnom/list?sort=ultfec&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_profec">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'profec'): ?>
      <?php echo link_to(__('Hasta'), 'nomnomcalnom/list?sort=profec&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Hasta'), 'nomnomcalnom/list?sort=profec&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_numsem">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'numsem'): ?>
      <?php echo link_to(__('Este mes tiene'), 'nomnomcalnom/list?sort=numsem&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Este mes tiene'), 'nomnomcalnom/list?sort=numsem&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_ordpag">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'ordpag'): ?>
      <?php echo link_to(__('Ordpag'), 'nomnomcalnom/list?sort=ordpag&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Ordpag'), 'nomnomcalnom/list?sort=ordpag&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_tipcau">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'tipcau'): ?>
      <?php echo link_to(__('Tipcau'), 'nomnomcalnom/list?sort=tipcau&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Tipcau'), 'nomnomcalnom/list?sort=tipcau&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_refcau">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'refcau'): ?>
      <?php echo link_to(__('Refcau'), 'nomnomcalnom/list?sort=refcau&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Refcau'), 'nomnomcalnom/list?sort=refcau&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_tipprc">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'tipprc'): ?>
      <?php echo link_to(__('Tipprc'), 'nomnomcalnom/list?sort=tipprc&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Tipprc'), 'nomnomcalnom/list?sort=tipprc&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_refprc">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'refprc'): ?>
      <?php echo link_to(__('Refprc'), 'nomnomcalnom/list?sort=refprc&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Refprc'), 'nomnomcalnom/list?sort=refprc&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_tipcom">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'tipcom'): ?>
      <?php echo link_to(__('Tipcom'), 'nomnomcalnom/list?sort=tipcom&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Tipcom'), 'nomnomcalnom/list?sort=tipcom&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_refcom">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'refcom'): ?>
      <?php echo link_to(__('Refcom'), 'nomnomcalnom/list?sort=refcom&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Refcom'), 'nomnomcalnom/list?sort=refcom&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_codban">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'codban'): ?>
      <?php echo link_to(__('Codban'), 'nomnomcalnom/list?sort=codban&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Codban'), 'nomnomcalnom/list?sort=codban&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_numcue">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'numcue'): ?>
      <?php echo link_to(__('Numcue'), 'nomnomcalnom/list?sort=numcue&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Numcue'), 'nomnomcalnom/list?sort=numcue&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_codcta">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'codcta'): ?>
      <?php echo link_to(__('Codcta'), 'nomnomcalnom/list?sort=codcta&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Codcta'), 'nomnomcalnom/list?sort=codcta&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'nomnomcalnom/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'nomnomcalnom/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
