<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:46:12
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomhojint 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<td colspan="7">
    <?php echo get_partial('fotemp', array('type' => 'list', 'nphojint' => $nphojint)) ?>
     - 
    <?php echo link_to($nphojint->getCodemp() ? $nphojint->getCodemp() : __('-'), 'nomhojint/edit?id='.$nphojint->getId()) ?>
     - 
    <?php echo $nphojint->getNomemp() ?>
     - 
    <?php echo $nphojint->getCodniv() ?>
     - 
    <?php echo $nphojint->getDesniv() ?>
     - 
    <?php echo $nphojint->getStaemp2() ?>
     - 
    <?php echo $nphojint->getDestipemp() ?>
     - 
</td>