<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:44:55
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomdefesptipnom 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_codnom">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'codnom'): ?>
      <?php echo link_to(__('Código'), 'nomdefesptipnom/list?sort=codnom&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Código'), 'nomdefesptipnom/list?sort=codnom&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nomnom">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'nomnom'): ?>
      <?php echo link_to(__('Nombre'), 'nomdefesptipnom/list?sort=nomnom&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nombre'), 'nomdefesptipnom/list?sort=nomnom&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_ultfec">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'ultfec'): ?>
      <?php echo link_to(__('Desde'), 'nomdefesptipnom/list?sort=ultfec&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Desde'), 'nomdefesptipnom/list?sort=ultfec&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_profec">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npnomina/sort') == 'profec'): ?>
      <?php echo link_to(__('Hasta'), 'nomdefesptipnom/list?sort=profec&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npnomina/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Hasta'), 'nomdefesptipnom/list?sort=profec&type=asc') ?>
      <?php endif; ?>
          </th>
