<?php
// auto-generated by PropelCidesa
// date: 2017/02/13 06:39:11
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _edit_form.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php echo form_tag('fapais/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'return false;',
)) ?>

<?php echo object_input_hidden_tag($fapais, 'getId') ?>

<?php
  $fields = FapaisPeer::getFieldNames();

  if(array_search('Codalmusu', $fields))
  {  ?>
  <h2 class="h2" onclick="javascript: return $('divusualms').toggle();"><?php echo __('Almacenes') ?></h2>
  <fieldset id="sf_fieldset_usualms" class="">
  <div class="form-row" id="divusualms">
    <?php echo label_for('fapais[codalmusu]', __('Almacenes Por Usuario: '), 'class="required" Style="text-align:left; width:150px"') ?>
    <div class="content">
    <?php
      $almacenes = $sf_user->getAttribute('usualms',array());
      if(count($almacenes)>0){
        $keys = array_keys($almacenes);
        $codalm = $keys[0];
      }else $codalm = '';
      if($codalm == '') echo label_for('fapais[codalmusu]', __('Usuario sin Almacen Asociado'), 'class="required" Style="text-align:left; width:150px"').'<br><br><br>';
      else echo select_tag('fapais[codalmusu]',options_for_select($almacenes,$fapais->getCodalmusu()!='' ? $fapais->getCodalmusu() : $codalm), ( ($fapais->getId()) ? 'disabled=true' : '').' style=width:500px');
    ?>
    </div>
  </div>
  </fieldset>
<?php } ?>



<fieldset id="sf_fieldset_none" class="">

<div class="form-row" id="divNONE">
<div id="divnompai">
  <?php if($labels['fapais{nompai}']!='.:') { ?>
  <?php echo label_for('fapais[nompai]', __($labels['fapais{nompai}' ]), 'class="required" Style="text-align:left; width:150px"') ?>
  <div class="content<?php if ($sf_request->hasError('fapais{nompai}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('fapais{nompai}')): ?>
    <?php echo form_error('fapais{nompai}', array('class' => 'form-error-msg')) ?>
  <?php endif; }?>  
  
   
  
  <?php $value = object_input_tag($fapais, 'getNompai', array (
  'size' => 20,
  'control_name' => 'fapais[nompai]',
)); echo $value ? $value : '&nbsp;' ?>
      
		
  <?php if($labels['fapais{nompai}']!='.:') { ?>  
  

   
  </div>
  <?php  } ?> 

</div>
<br/>
</div>
</fieldset>

<?php include_partial('edit_actions', array('fapais' => $fapais)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($fapais->getId()): ?>
<?php echo button_to(__('delete'), 'fapais/delete?id='.$fapais->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>

