<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 05:46:27
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomnomcalnomind 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_td_stacked.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

<td colspan="17">
    <?php echo $npnomina->getCodnom() ?>
     - 
    <?php echo $npnomina->getNomnom() ?>
     - 
    <?php echo $npnomina->getFrecal() ?>
     - 
    <?php echo ($npnomina->getUltfec() !== null && $npnomina->getUltfec() !== '') ? format_date($npnomina->getUltfec(), "dd/MM/yyyy") : '' ?>
     - 
    <?php echo ($npnomina->getProfec() !== null && $npnomina->getProfec() !== '') ? format_date($npnomina->getProfec(), "dd/MM/yyyy") : '' ?>
     - 
    <?php echo $npnomina->getNumsem() ?>
     - 
    <?php echo $npnomina->getOrdpag() ?>
     - 
    <?php echo $npnomina->getTipcau() ?>
     - 
    <?php echo $npnomina->getRefcau() ?>
     - 
    <?php echo $npnomina->getTipprc() ?>
     - 
    <?php echo $npnomina->getRefprc() ?>
     - 
    <?php echo $npnomina->getTipcom() ?>
     - 
    <?php echo $npnomina->getRefcom() ?>
     - 
    <?php echo $npnomina->getCodban() ?>
     - 
    <?php echo $npnomina->getNumcue() ?>
     - 
    <?php echo $npnomina->getCodcta() ?>
     - 
    <?php echo link_to($npnomina->getId() ? $npnomina->getId() : __('-'), 'nomnomcalnomind/edit?id='.$npnomina->getId()) ?>
     - 
</td>