<?php
// auto-generated by PropelCidesa
// date: 2014/11/17 08:56:15
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage vistas
 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: editSuccess.php 32815 2009-09-08 16:52:04Z lhernandez $
 * @copyright  Copyright 2007, Cide S.A.
 *
 */
 ?>

<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'Catalogo') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1>
<?php 
$cambiareti=H::getConfApp2('cameti', 'cuentasxcobrar', 'fatippag');
if ($cambiareti=="S") {?>
<?php echo __('Edición de Forma de Cobro', 
array()) ?>
<?php }else {?>
<?php echo __('Edición de Forma de Pago',
array()) ?>
<?php }?>
</h1>


<div id="sf_admin_header">
<?php include_partial('fatippag/edit_header', array('fatippag' => $fatippag, 'labels' => $labels, 'params' => $params)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('fatippag/edit_messages', array('fatippag' => $fatippag, 'labels' => $labels, 'params' => $params)) ?>
<?php include_partial('fatippag/edit_form', array('fatippag' => $fatippag, 'labels' => $labels, 'params' => $params)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('fatippag/edit_footer', array('fatippag' => $fatippag, 'labels' => $labels, 'params' => $params)) ?>
</div>

</div>
