<?php
// auto-generated by sfPropelAdmin
// date: 2017/02/13 06:11:03
?>
<?php

/**
 *
 * @package    Roraima
 * @subpackage autoNomcomocp 
 * @author     $Author: lhernandez $ <desarrollo@cidesa.com.ve>
 * @version    SVN: $Id: _list_th_tabular.php 32371 2009-09-01 16:06:59Z lhernandez $
 * @copyright  Copyright 2007, Cidesa C.A.
 *
 */
 ?>

  <th id="sf_admin_list_th_codtipcar">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npcomocp/sort') == 'codtipcar'): ?>
      <?php echo link_to(__('Cod. Tipo Cargo'), 'nomcomocp/list?sort=codtipcar&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npcomocp/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npcomocp/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Cod. Tipo Cargo'), 'nomcomocp/list?sort=codtipcar&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_destipcar">
        <?php echo __('Descripción') ?>
          </th>
  <th id="sf_admin_list_th_fecdes">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/npcomocp/sort') == 'fecdes'): ?>
      <?php echo link_to(__('Vigencia'), 'nomcomocp/list?sort=fecdes&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/npcomocp/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/npcomocp/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Vigencia'), 'nomcomocp/list?sort=fecdes&type=asc') ?>
      <?php endif; ?>
          </th>
